// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.29.3
// source: common.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AlertSeverity grades how serious an alert is. Used by road alerts, region
// incidents, and weather alerts (NWS severity is mapped onto this scale).
type AlertSeverity int32

const (
	AlertSeverity_ALERT_SEVERITY_UNSPECIFIED AlertSeverity = 0
	AlertSeverity_INFO                       AlertSeverity = 1
	AlertSeverity_WARNING                    AlertSeverity = 2
	AlertSeverity_CRITICAL                   AlertSeverity = 3
)

// Enum value maps for AlertSeverity.
var (
	AlertSeverity_name = map[int32]string{
		0: "ALERT_SEVERITY_UNSPECIFIED",
		1: "INFO",
		2: "WARNING",
		3: "CRITICAL",
	}
	AlertSeverity_value = map[string]int32{
		"ALERT_SEVERITY_UNSPECIFIED": 0,
		"INFO":                       1,
		"WARNING":                    2,
		"CRITICAL":                   3,
	}
)

func (x AlertSeverity) Enum() *AlertSeverity {
	p := new(AlertSeverity)
	*p = x
	return p
}

func (x AlertSeverity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlertSeverity) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (AlertSeverity) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x AlertSeverity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlertSeverity.Descriptor instead.
func (AlertSeverity) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

// AlertSource identifies which upstream feed produced a weather alert.
type AlertSource int32

const (
	AlertSource_ALERT_SOURCE_UNSPECIFIED AlertSource = 0
	AlertSource_NWS                      AlertSource = 1 // National Weather Service (authoritative)
	AlertSource_OPENWEATHERMAP           AlertSource = 2 // OpenWeatherMap One Call API
)

// Enum value maps for AlertSource.
var (
	AlertSource_name = map[int32]string{
		0: "ALERT_SOURCE_UNSPECIFIED",
		1: "NWS",
		2: "OPENWEATHERMAP",
	}
	AlertSource_value = map[string]int32{
		"ALERT_SOURCE_UNSPECIFIED": 0,
		"NWS":                      1,
		"OPENWEATHERMAP":           2,
	}
)

func (x AlertSource) Enum() *AlertSource {
	p := new(AlertSource)
	*p = x
	return p
}

func (x AlertSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlertSource) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[1].Descriptor()
}

func (AlertSource) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[1]
}

func (x AlertSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlertSource.Descriptor instead.
func (AlertSource) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

// FireWeatherState escalates Normal -> Elevated -> Red Flag.
type FireWeatherState int32

const (
	FireWeatherState_FIRE_WEATHER_STATE_UNSPECIFIED FireWeatherState = 0
	FireWeatherState_NORMAL                         FireWeatherState = 1 // No fire-weather product in effect
	FireWeatherState_ELEVATED                       FireWeatherState = 2 // Fire Weather Watch in effect
	FireWeatherState_RED_FLAG                       FireWeatherState = 3 // Red Flag Warning in effect
)

// Enum value maps for FireWeatherState.
var (
	FireWeatherState_name = map[int32]string{
		0: "FIRE_WEATHER_STATE_UNSPECIFIED",
		1: "NORMAL",
		2: "ELEVATED",
		3: "RED_FLAG",
	}
	FireWeatherState_value = map[string]int32{
		"FIRE_WEATHER_STATE_UNSPECIFIED": 0,
		"NORMAL":                         1,
		"ELEVATED":                       2,
		"RED_FLAG":                       3,
	}
)

func (x FireWeatherState) Enum() *FireWeatherState {
	p := new(FireWeatherState)
	*p = x
	return p
}

func (x FireWeatherState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FireWeatherState) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[2].Descriptor()
}

func (FireWeatherState) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[2]
}

func (x FireWeatherState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FireWeatherState.Descriptor instead.
func (FireWeatherState) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

// IncidentStatus is the lifecycle state of a region-wide incident. The feeds
// only list active incidents today.
type IncidentStatus int32

const (
	IncidentStatus_INCIDENT_STATUS_UNSPECIFIED IncidentStatus = 0
	IncidentStatus_ACTIVE                      IncidentStatus = 1
)

// Enum value maps for IncidentStatus.
var (
	IncidentStatus_name = map[int32]string{
		0: "INCIDENT_STATUS_UNSPECIFIED",
		1: "ACTIVE",
	}
	IncidentStatus_value = map[string]int32{
		"INCIDENT_STATUS_UNSPECIFIED": 0,
		"ACTIVE":                      1,
	}
)

func (x IncidentStatus) Enum() *IncidentStatus {
	p := new(IncidentStatus)
	*p = x
	return p
}

func (x IncidentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IncidentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[3].Descriptor()
}

func (IncidentStatus) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[3]
}

func (x IncidentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IncidentStatus.Descriptor instead.
func (IncidentStatus) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

// AlertImpact is the AI-assessed impact of a road alert.
type AlertImpact int32

const (
	AlertImpact_ALERT_IMPACT_UNSPECIFIED AlertImpact = 0
	AlertImpact_IMPACT_NONE              AlertImpact = 1
	AlertImpact_IMPACT_LIGHT             AlertImpact = 2
	AlertImpact_IMPACT_MODERATE          AlertImpact = 3
	AlertImpact_IMPACT_SEVERE            AlertImpact = 4
)

// Enum value maps for AlertImpact.
var (
	AlertImpact_name = map[int32]string{
		0: "ALERT_IMPACT_UNSPECIFIED",
		1: "IMPACT_NONE",
		2: "IMPACT_LIGHT",
		3: "IMPACT_MODERATE",
		4: "IMPACT_SEVERE",
	}
	AlertImpact_value = map[string]int32{
		"ALERT_IMPACT_UNSPECIFIED": 0,
		"IMPACT_NONE":              1,
		"IMPACT_LIGHT":             2,
		"IMPACT_MODERATE":          3,
		"IMPACT_SEVERE":            4,
	}
)

func (x AlertImpact) Enum() *AlertImpact {
	p := new(AlertImpact)
	*p = x
	return p
}

func (x AlertImpact) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlertImpact) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[4].Descriptor()
}

func (AlertImpact) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[4]
}

func (x AlertImpact) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlertImpact.Descriptor instead.
func (AlertImpact) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4}
}

// AlertDuration is the AI-assessed duration of a road alert.
type AlertDuration int32

const (
	AlertDuration_ALERT_DURATION_UNSPECIFIED AlertDuration = 0
	AlertDuration_DURATION_UNKNOWN           AlertDuration = 1
	AlertDuration_DURATION_UNDER_ONE_HOUR    AlertDuration = 2
	AlertDuration_DURATION_SEVERAL_HOURS     AlertDuration = 3
	AlertDuration_DURATION_ONGOING           AlertDuration = 4
)

// Enum value maps for AlertDuration.
var (
	AlertDuration_name = map[int32]string{
		0: "ALERT_DURATION_UNSPECIFIED",
		1: "DURATION_UNKNOWN",
		2: "DURATION_UNDER_ONE_HOUR",
		3: "DURATION_SEVERAL_HOURS",
		4: "DURATION_ONGOING",
	}
	AlertDuration_value = map[string]int32{
		"ALERT_DURATION_UNSPECIFIED": 0,
		"DURATION_UNKNOWN":           1,
		"DURATION_UNDER_ONE_HOUR":    2,
		"DURATION_SEVERAL_HOURS":     3,
		"DURATION_ONGOING":           4,
	}
)

func (x AlertDuration) Enum() *AlertDuration {
	p := new(AlertDuration)
	*p = x
	return p
}

func (x AlertDuration) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlertDuration) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[5].Descriptor()
}

func (AlertDuration) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[5]
}

func (x AlertDuration) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlertDuration.Descriptor instead.
func (AlertDuration) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{5}
}

// Geographic coordinates in WGS84 decimal degrees
type Coordinates struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Latitude  float64 `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`   // Latitude in decimal degrees (-90 to 90)
	Longitude float64 `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"` // Longitude in decimal degrees (-180 to 180)
}

func (x *Coordinates) Reset() {
	*x = Coordinates{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Coordinates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinates) ProtoMessage() {}

func (x *Coordinates) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinates.ProtoReflect.Descriptor instead.
func (*Coordinates) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *Coordinates) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Coordinates) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

// Geographic polyline for route and closure representations
type Polyline struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EncodedPolyline string         `protobuf:"bytes,1,opt,name=encoded_polyline,json=encodedPolyline,proto3" json:"encoded_polyline,omitempty"` // Google polyline encoded string
	Points          []*Coordinates `protobuf:"bytes,2,rep,name=points,proto3" json:"points,omitempty"`                                          // Decoded coordinate points
}

func (x *Polyline) Reset() {
	*x = Polyline{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Polyline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Polyline) ProtoMessage() {}

func (x *Polyline) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Polyline.ProtoReflect.Descriptor instead.
func (*Polyline) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *Polyline) GetEncodedPolyline() string {
	if x != nil {
		return x.EncodedPolyline
	}
	return ""
}

func (x *Polyline) GetPoints() []*Coordinates {
	if x != nil {
		return x.Points
	}
	return nil
}

var File_common_proto protoreflect.FileDescriptor

var file_common_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x22, 0x47, 0x0a, 0x0b, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69,
	0x6e, 0x61, 0x74, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x22,
	0x62, 0x0a, 0x08, 0x50, 0x6f, 0x6c, 0x79, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x65,
	0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x5f, 0x70, 0x6f, 0x6c, 0x79, 0x6c, 0x69, 0x6e, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x50, 0x6f,
	0x6c, 0x79, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x2b, 0x0a, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x52, 0x06, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x73, 0x2a, 0x54, 0x0a, 0x0d, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x53, 0x65, 0x76, 0x65,
	0x72, 0x69, 0x74, 0x79, 0x12, 0x1e, 0x0a, 0x1a, 0x41, 0x4c, 0x45, 0x52, 0x54, 0x5f, 0x53, 0x45,
	0x56, 0x45, 0x52, 0x49, 0x54, 0x59, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49,
	0x45, 0x44, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x4e, 0x46, 0x4f, 0x10, 0x01, 0x12, 0x0b,
	0x0a, 0x07, 0x57, 0x41, 0x52, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x43,
	0x52, 0x49, 0x54, 0x49, 0x43, 0x41, 0x4c, 0x10, 0x03, 0x2a, 0x48, 0x0a, 0x0b, 0x41, 0x6c, 0x65,
	0x72, 0x74, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x18, 0x41, 0x4c, 0x45, 0x52,
	0x54, 0x5f, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x4e, 0x57, 0x53, 0x10, 0x01, 0x12,
	0x12, 0x0a, 0x0e, 0x4f, 0x50, 0x45, 0x4e, 0x57, 0x45, 0x41, 0x54, 0x48, 0x45, 0x52, 0x4d, 0x41,
	0x50, 0x10, 0x02, 0x2a, 0x5e, 0x0a, 0x10, 0x46, 0x69, 0x72, 0x65, 0x57, 0x65, 0x61, 0x74, 0x68,
	0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x22, 0x0a, 0x1e, 0x46, 0x49, 0x52, 0x45, 0x5f,
	0x57, 0x45, 0x41, 0x54, 0x48, 0x45, 0x52, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x55, 0x4e,
	0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x4e,
	0x4f, 0x52, 0x4d, 0x41, 0x4c, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x45, 0x4c, 0x45, 0x56, 0x41,
	0x54, 0x45, 0x44, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x45, 0x44, 0x5f, 0x46, 0x4c, 0x41,
	0x47, 0x10, 0x03, 0x2a, 0x3d, 0x0a, 0x0e, 0x49, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1f, 0x0a, 0x1b, 0x49, 0x4e, 0x43, 0x49, 0x44, 0x45, 0x4e,
	0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45,
	0x10, 0x01, 0x2a, 0x76, 0x0a, 0x0b, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x49, 0x6d, 0x70, 0x61, 0x63,
	0x74, 0x12, 0x1c, 0x0a, 0x18, 0x41, 0x4c, 0x45, 0x52, 0x54, 0x5f, 0x49, 0x4d, 0x50, 0x41, 0x43,
	0x54, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x0f, 0x0a, 0x0b, 0x49, 0x4d, 0x50, 0x41, 0x43, 0x54, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x01,
	0x12, 0x10, 0x0a, 0x0c, 0x49, 0x4d, 0x50, 0x41, 0x43, 0x54, 0x5f, 0x4c, 0x49, 0x47, 0x48, 0x54,
	0x10, 0x02, 0x12, 0x13, 0x0a, 0x0f, 0x49, 0x4d, 0x50, 0x41, 0x43, 0x54, 0x5f, 0x4d, 0x4f, 0x44,
	0x45, 0x52, 0x41, 0x54, 0x45, 0x10, 0x03, 0x12, 0x11, 0x0a, 0x0d, 0x49, 0x4d, 0x50, 0x41, 0x43,
	0x54, 0x5f, 0x53, 0x45, 0x56, 0x45, 0x52, 0x45, 0x10, 0x04, 0x2a, 0x94, 0x01, 0x0a, 0x0d, 0x41,
	0x6c, 0x65, 0x72, 0x74, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x1a,
	0x41, 0x4c, 0x45, 0x52, 0x54, 0x5f, 0x44, 0x55, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x55,
	0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10,
	0x44, 0x55, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e,
	0x10, 0x01, 0x12, 0x1b, 0x0a, 0x17, 0x44, 0x55, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x55,
	0x4e, 0x44, 0x45, 0x52, 0x5f, 0x4f, 0x4e, 0x45, 0x5f, 0x48, 0x4f, 0x55, 0x52, 0x10, 0x02, 0x12,
	0x1a, 0x0a, 0x16, 0x44, 0x55, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x45, 0x56, 0x45,
	0x52, 0x41, 0x4c, 0x5f, 0x48, 0x4f, 0x55, 0x52, 0x53, 0x10, 0x03, 0x12, 0x14, 0x0a, 0x10, 0x44,
	0x55, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x4f, 0x4e, 0x47, 0x4f, 0x49, 0x4e, 0x47, 0x10,
	0x04, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x64, 0x70, 0x75, 0x70, 0x2f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x65, 0x72, 0x73, 0x6e, 0x2e, 0x6e,
	0x65, 0x74, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData = file_common_proto_rawDesc
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_proto_rawDescData)
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_proto_goTypes = []interface{}{
	(AlertSeverity)(0),    // 0: api.v1.AlertSeverity
	(AlertSource)(0),      // 1: api.v1.AlertSource
	(FireWeatherState)(0), // 2: api.v1.FireWeatherState
	(IncidentStatus)(0),   // 3: api.v1.IncidentStatus
	(AlertImpact)(0),      // 4: api.v1.AlertImpact
	(AlertDuration)(0),    // 5: api.v1.AlertDuration
	(*Coordinates)(nil),   // 6: api.v1.Coordinates
	(*Polyline)(nil),      // 7: api.v1.Polyline
}
var file_common_proto_depIdxs = []int32{
	6, // 0: api.v1.Polyline.points:type_name -> api.v1.Coordinates
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Coordinates); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Polyline); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_proto_rawDesc,
			NumEnums:      6,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_rawDesc = nil
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
