// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.3
// source: roads.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	RoadsService_ListRoads_FullMethodName            = "/api.v1.RoadsService/ListRoads"
	RoadsService_GetRoad_FullMethodName              = "/api.v1.RoadsService/GetRoad"
	RoadsService_GetProcessingMetrics_FullMethodName = "/api.v1.RoadsService/GetProcessingMetrics"
	RoadsService_ListIncidents_FullMethodName        = "/api.v1.RoadsService/ListIncidents"
)

// RoadsServiceClient is the client API for RoadsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RoadsServiceClient interface {
	// ListRoads returns current conditions for all configured roads
	ListRoads(ctx context.Context, in *ListRoadsRequest, opts ...grpc.CallOption) (*ListRoadsResponse, error)
	// GetRoad returns current conditions for a specific road
	GetRoad(ctx context.Context, in *GetRoadRequest, opts ...grpc.CallOption) (*GetRoadResponse, error)
	// GetProcessingMetrics returns alert processing metrics.
	// Mapped to /api/v1/metrics (not /api/v1/roads/metrics) so it does not collide
	// with the /api/v1/roads/{road_id} id space.
	GetProcessingMetrics(ctx context.Context, in *GetProcessingMetricsRequest, opts ...grpc.CallOption) (*ProcessingMetrics, error)
	// ListIncidents returns region-wide CHP/Caltrans dispatch incidents for a
	// configured area, e.g. /api/v1/incidents/mother-lode. The area is a path
	// param (an identity, like a road or location id) for consistency with
	// GetRoad/GetLocationWeather. Unlike the alerts embedded in each Road, this is
	// not scoped to a monitored route - it surfaces every incident within the
	// area as a flat, structured list without per-route classification or AI
	// enhancement (kept lightweight for a region-wide view).
	ListIncidents(ctx context.Context, in *ListIncidentsRequest, opts ...grpc.CallOption) (*ListIncidentsResponse, error)
}

type roadsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRoadsServiceClient(cc grpc.ClientConnInterface) RoadsServiceClient {
	return &roadsServiceClient{cc}
}

func (c *roadsServiceClient) ListRoads(ctx context.Context, in *ListRoadsRequest, opts ...grpc.CallOption) (*ListRoadsResponse, error) {
	out := new(ListRoadsResponse)
	err := c.cc.Invoke(ctx, RoadsService_ListRoads_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roadsServiceClient) GetRoad(ctx context.Context, in *GetRoadRequest, opts ...grpc.CallOption) (*GetRoadResponse, error) {
	out := new(GetRoadResponse)
	err := c.cc.Invoke(ctx, RoadsService_GetRoad_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roadsServiceClient) GetProcessingMetrics(ctx context.Context, in *GetProcessingMetricsRequest, opts ...grpc.CallOption) (*ProcessingMetrics, error) {
	out := new(ProcessingMetrics)
	err := c.cc.Invoke(ctx, RoadsService_GetProcessingMetrics_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roadsServiceClient) ListIncidents(ctx context.Context, in *ListIncidentsRequest, opts ...grpc.CallOption) (*ListIncidentsResponse, error) {
	out := new(ListIncidentsResponse)
	err := c.cc.Invoke(ctx, RoadsService_ListIncidents_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoadsServiceServer is the server API for RoadsService service.
// All implementations must embed UnimplementedRoadsServiceServer
// for forward compatibility
type RoadsServiceServer interface {
	// ListRoads returns current conditions for all configured roads
	ListRoads(context.Context, *ListRoadsRequest) (*ListRoadsResponse, error)
	// GetRoad returns current conditions for a specific road
	GetRoad(context.Context, *GetRoadRequest) (*GetRoadResponse, error)
	// GetProcessingMetrics returns alert processing metrics.
	// Mapped to /api/v1/metrics (not /api/v1/roads/metrics) so it does not collide
	// with the /api/v1/roads/{road_id} id space.
	GetProcessingMetrics(context.Context, *GetProcessingMetricsRequest) (*ProcessingMetrics, error)
	// ListIncidents returns region-wide CHP/Caltrans dispatch incidents for a
	// configured area, e.g. /api/v1/incidents/mother-lode. The area is a path
	// param (an identity, like a road or location id) for consistency with
	// GetRoad/GetLocationWeather. Unlike the alerts embedded in each Road, this is
	// not scoped to a monitored route - it surfaces every incident within the
	// area as a flat, structured list without per-route classification or AI
	// enhancement (kept lightweight for a region-wide view).
	ListIncidents(context.Context, *ListIncidentsRequest) (*ListIncidentsResponse, error)
	mustEmbedUnimplementedRoadsServiceServer()
}

// UnimplementedRoadsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRoadsServiceServer struct {
}

func (UnimplementedRoadsServiceServer) ListRoads(context.Context, *ListRoadsRequest) (*ListRoadsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRoads not implemented")
}
func (UnimplementedRoadsServiceServer) GetRoad(context.Context, *GetRoadRequest) (*GetRoadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoad not implemented")
}
func (UnimplementedRoadsServiceServer) GetProcessingMetrics(context.Context, *GetProcessingMetricsRequest) (*ProcessingMetrics, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProcessingMetrics not implemented")
}
func (UnimplementedRoadsServiceServer) ListIncidents(context.Context, *ListIncidentsRequest) (*ListIncidentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListIncidents not implemented")
}
func (UnimplementedRoadsServiceServer) mustEmbedUnimplementedRoadsServiceServer() {}

// UnsafeRoadsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoadsServiceServer will
// result in compilation errors.
type UnsafeRoadsServiceServer interface {
	mustEmbedUnimplementedRoadsServiceServer()
}

func RegisterRoadsServiceServer(s grpc.ServiceRegistrar, srv RoadsServiceServer) {
	s.RegisterService(&RoadsService_ServiceDesc, srv)
}

func _RoadsService_ListRoads_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRoadsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoadsServiceServer).ListRoads(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoadsService_ListRoads_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoadsServiceServer).ListRoads(ctx, req.(*ListRoadsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoadsService_GetRoad_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoadsServiceServer).GetRoad(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoadsService_GetRoad_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoadsServiceServer).GetRoad(ctx, req.(*GetRoadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoadsService_GetProcessingMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProcessingMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoadsServiceServer).GetProcessingMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoadsService_GetProcessingMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoadsServiceServer).GetProcessingMetrics(ctx, req.(*GetProcessingMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoadsService_ListIncidents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIncidentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoadsServiceServer).ListIncidents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoadsService_ListIncidents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoadsServiceServer).ListIncidents(ctx, req.(*ListIncidentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RoadsService_ServiceDesc is the grpc.ServiceDesc for RoadsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoadsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.RoadsService",
	HandlerType: (*RoadsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListRoads",
			Handler:    _RoadsService_ListRoads_Handler,
		},
		{
			MethodName: "GetRoad",
			Handler:    _RoadsService_GetRoad_Handler,
		},
		{
			MethodName: "GetProcessingMetrics",
			Handler:    _RoadsService_GetProcessingMetrics_Handler,
		},
		{
			MethodName: "ListIncidents",
			Handler:    _RoadsService_ListIncidents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "roads.proto",
}
