// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: roads.proto

package v1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enumerations
type RoadStatus int32

const (
	RoadStatus_ROAD_STATUS_UNSPECIFIED RoadStatus = 0
	RoadStatus_OPEN                    RoadStatus = 1
	RoadStatus_CLOSED                  RoadStatus = 2
	RoadStatus_RESTRICTED              RoadStatus = 3
	RoadStatus_MAINTENANCE             RoadStatus = 4
)

// Enum value maps for RoadStatus.
var (
	RoadStatus_name = map[int32]string{
		0: "ROAD_STATUS_UNSPECIFIED",
		1: "OPEN",
		2: "CLOSED",
		3: "RESTRICTED",
		4: "MAINTENANCE",
	}
	RoadStatus_value = map[string]int32{
		"ROAD_STATUS_UNSPECIFIED": 0,
		"OPEN":                    1,
		"CLOSED":                  2,
		"RESTRICTED":              3,
		"MAINTENANCE":             4,
	}
)

func (x RoadStatus) Enum() *RoadStatus {
	p := new(RoadStatus)
	*p = x
	return p
}

func (x RoadStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoadStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_roads_proto_enumTypes[0].Descriptor()
}

func (RoadStatus) Type() protoreflect.EnumType {
	return &file_roads_proto_enumTypes[0]
}

func (x RoadStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoadStatus.Descriptor instead.
func (RoadStatus) EnumDescriptor() ([]byte, []int) {
	return file_roads_proto_rawDescGZIP(), []int{0}
}

type ChainControlStatus int32

const (
	ChainControlStatus_CHAIN_CONTROL_UNSPECIFIED ChainControlStatus = 0
	ChainControlStatus_NONE                      ChainControlStatus = 1
	ChainControlStatus_ADVISED                   ChainControlStatus = 2
	ChainControlStatus_REQUIRED                  ChainControlStatus = 3
	ChainControlStatus_PROHIBITED                ChainControlStatus = 4
)

// Enum value maps for ChainControlStatus.
var (
	ChainControlStatus_name = map[int32]string{
		0: "CHAIN_CONTROL_UNSPECIFIED",
		1: "NONE",
		2: "ADVISED",
		3: "REQUIRED",
		4: "PROHIBITED",
	}
	ChainControlStatus_value = map[string]int32{
		"CHAIN_CONTROL_UNSPECIFIED": 0,
		"NONE":                      1,
		"ADVISED":                   2,
		"REQUIRED":                  3,
		"PROHIBITED":                4,
	}
)

func (x ChainControlStatus) Enum() *ChainControlStatus {
	p := new(ChainControlStatus)
	*p = x
	return p
}

func (x ChainControlStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChainControlStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_roads_proto_enumTypes[1].Descriptor()
}

func (ChainControlStatus) Type() protoreflect.EnumType {
	return &file_roads_proto_enumTypes[1]
}

func (x ChainControlStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChainControlStatus.Descriptor instead.
func (ChainControlStatus) EnumDescriptor() ([]byte, []int) {
	return file_roads_proto_rawDescGZIP(), []int{1}
}

// ChainControlLevel indicates the specific chain control requirement level
type ChainControlLevel int32

const (
	ChainControlLevel_CHAIN_CONTROL_LEVEL_UNSPECIFIED ChainControlLevel = 0
	ChainControlLevel_CHAIN_CONTROL_LEVEL_NONE        ChainControlLevel = 1 // No chain control in effect
	ChainControlLevel_CHAIN_CONTROL_LEVEL_R1          ChainControlLevel = 2 // Chains required except vehicles with snow tires
	ChainControlLevel_CHAIN_CONTROL_LEVEL_R2          ChainControlLevel = 3 // Chains required except 4WD/AWD with snow tires on all wheels
	ChainControlLevel_CHAIN_CONTROL_LEVEL_R3          ChainControlLevel = 4 // Chains required on all vehicles, no exceptions
)

// Enum value maps for ChainControlLevel.
var (
	ChainControlLevel_name = map[int32]string{
		0: "CHAIN_CONTROL_LEVEL_UNSPECIFIED",
		1: "CHAIN_CONTROL_LEVEL_NONE",
		2: "CHAIN_CONTROL_LEVEL_R1",
		3: "CHAIN_CONTROL_LEVEL_R2",
		4: "CHAIN_CONTROL_LEVEL_R3",
	}
	ChainControlLevel_value = map[string]int32{
		"CHAIN_CONTROL_LEVEL_UNSPECIFIED": 0,
		"CHAIN_CONTROL_LEVEL_NONE":        1,
		"CHAIN_CONTROL_LEVEL_R1":          2,
		"CHAIN_CONTROL_LEVEL_R2":          3,
		"CHAIN_CONTROL_LEVEL_R3":          4,
	}
)

func (x ChainControlLevel) Enum() *ChainControlLevel {
	p := new(ChainControlLevel)
	*p = x
	return p
}

func (x ChainControlLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChainControlLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_roads_proto_enumTypes[2].Descriptor()
}

func (ChainControlLevel) Type() protoreflect.EnumType {
	return &file_roads_proto_enumTypes[2]
}

func (x ChainControlLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChainControlLevel.Descriptor instead.
func (ChainControlLevel) EnumDescriptor() ([]byte, []int) {
	return file_roads_proto_rawDescGZIP(), []int{2}
}

type CongestionLevel int32

const (
	CongestionLevel_CONGESTION_LEVEL_UNSPECIFIED CongestionLevel = 0
	CongestionLevel_CLEAR                        CongestionLevel = 1
	CongestionLevel_LIGHT                        CongestionLevel = 2
	CongestionLevel_MODERATE                     CongestionLevel = 3
	CongestionLevel_HEAVY                        CongestionLevel = 4
	CongestionLevel_SEVERE                       CongestionLevel = 5
)

// Enum value maps for CongestionLevel.
var (
	CongestionLevel_name = map[int32]string{
		0: "CONGESTION_LEVEL_UNSPECIFIED",
		1: "CLEAR",
		2: "LIGHT",
		3: "MODERATE",
		4: "HEAVY",
		5: "SEVERE",
	}
	CongestionLevel_value = map[string]int32{
		"CONGESTION_LEVEL_UNSPECIFIED": 0,
		"CLEAR":                        1,
		"LIGHT":                        2,
		"MODERATE":                     3,
		"HEAVY":                        4,
		"SEVERE":                       5,
	}
)

func (x CongestionLevel) Enum() *CongestionLevel {
	p := new(CongestionLevel)
	*p = x
	return p
}

func (x CongestionLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CongestionLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_roads_proto_enumTypes[3].Descriptor()
}

func (CongestionLevel) Type() protoreflect.EnumType {
	return &file_roads_proto_enumTypes[3]
}

func (x CongestionLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CongestionLevel.Descriptor instead.
func (CongestionLevel) EnumDescriptor() ([]byte, []int) {
	return file_roads_proto_rawDescGZIP(), []int{3}
}

type AlertType int32

const (
	AlertType_ALERT_TYPE_UNSPECIFIED AlertType = 0
	AlertType_CLOSURE                AlertType = 1
	AlertType_CONSTRUCTION           AlertType = 2
	AlertType_INCIDENT               AlertType = 3
	AlertType_WEATHER                AlertType = 4
)

// Enum value maps for AlertType.
var (
	AlertType_name = map[int32]string{
		0: "ALERT_TYPE_UNSPECIFIED",
		1: "CLOSURE",
		2: "CONSTRUCTION",
		3: "INCIDENT",
		4: "WEATHER",
	}
	AlertType_value = map[string]int32{
		"ALERT_TYPE_UNSPECIFIED": 0,
		"CLOSURE":                1,
		"CONSTRUCTION":           2,
		"INCIDENT":               3,
		"WEATHER":                4,
	}
)

func (x AlertType) Enum() *AlertType {
	p := new(AlertType)
	*p = x
	return p
}

func (x AlertType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlertType) Descriptor() protoreflect.EnumDescriptor {
	return file_roads_proto_enumTypes[4].Descriptor()
}

func (AlertType) Type() protoreflect.EnumType {
	return &file_roads_proto_enumTypes[4]
}

func (x AlertType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlertType.Descriptor instead.
func (AlertType) EnumDescriptor() ([]byte, []int) {
	return file_roads_proto_rawDescGZIP(), []int{4}
}

type AlertClassification int32

const (
	AlertClassification_ALERT_CLASSIFICATION_UNSPECIFIED AlertClassification = 0
	AlertClassification_ON_ROUTE                         AlertClassification = 1 // Directly affects route path (< 100m from route)
	AlertClassification_NEARBY                           AlertClassification = 2 // In surrounding area but not blocking route (< route threshold)
	AlertClassification_DISTANT                          AlertClassification = 3 // Too far from route to be relevant (> route threshold)
)

// Enum value maps for AlertClassification.
var (
	AlertClassification_name = map[int32]string{
		0: "ALERT_CLASSIFICATION_UNSPECIFIED",
		1: "ON_ROUTE",
		2: "NEARBY",
		3: "DISTANT",
	}
	AlertClassification_value = map[string]int32{
		"ALERT_CLASSIFICATION_UNSPECIFIED": 0,
		"ON_ROUTE":                         1,
		"NEARBY":                           2,
		"DISTANT":                          3,
	}
)

func (x AlertClassification) Enum() *AlertClassification {
	p := new(AlertClassification)
	*p = x
	return p
}

func (x AlertClassification) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlertClassification) Descriptor() protoreflect.EnumDescriptor {
	return file_roads_proto_enumTypes[5].Descriptor()
}

func (AlertClassification) Type() protoreflect.EnumType {
	return &file_roads_proto_enumTypes[5]
}

func (x AlertClassification) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlertClassification.Descriptor instead.
func (AlertClassification) EnumDescriptor() ([]byte, []int) {
	return file_roads_proto_rawDescGZIP(), []int{5}
}

// Request messages
type ListRoadsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoadsRequest) Reset() {
	*x = ListRoadsRequest{}
	mi := &file_roads_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoadsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoadsRequest) ProtoMessage() {}

func (x *ListRoadsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_roads_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoadsRequest.ProtoReflect.Descriptor instead.
func (*ListRoadsRequest) Descriptor() ([]byte, []int) {
	return file_roads_proto_rawDescGZIP(), []int{0}
}

type GetRoadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoadId        string                 `protobuf:"bytes,1,opt,name=road_id,json=roadId,proto3" json:"road_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoadRequest) Reset() {
	*x = GetRoadRequest{}
	mi := &file_roads_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoadRequest) ProtoMessage() {}

func (x *GetRoadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_roads_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoadRequest.ProtoReflect.Descriptor instead.
func (*GetRoadRequest) Descriptor() ([]byte, []int) {
	return file_roads_proto_rawDescGZIP(), []int{1}
}

func (x *GetRoadRequest) GetRoadId() string {
	if x != nil {
		return x.RoadId
	}
	return ""
}

type GetProcessingMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProcessingMetricsRequest) Reset() {
	*x = GetProcessingMetricsRequest{}
	mi := &file_roads_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProcessingMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProcessingMetricsRequest) ProtoMessage() {}

func (x *GetProcessingMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_roads_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProcessingMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetProcessingMetricsRequest) Descriptor() ([]byte, []int) {
	return file_roads_proto_rawDescGZIP(), []int{2}
}

// ListIncidentsRequest selects the configured area whose incidents to return.
type ListIncidentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Area          string                 `protobuf:"bytes,1,opt,name=area,proto3" json:"area,omitempty"` // Area id path param (e.g. "mother-lode"). Unknown id -> 404.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIncidentsRequest) Reset() {
	*x = ListIncidentsRequest{}
	mi := &file_roads_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIncidentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIncidentsRequest) ProtoMessage() {}

func (x *ListIncidentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_roads_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIncidentsRequest.ProtoReflect.Descriptor instead.
func (*ListIncidentsRequest) Descriptor() ([]byte, []int) {
	return file_roads_proto_rawDescGZIP(), []int{3}
}

func (x *ListIncidentsRequest) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

// Response messages
type ListRoadsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roads         []*Road                `protobuf:"bytes,1,rep,name=roads,proto3" json:"roads,omitempty"`
	LastUpdated   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoadsResponse) Reset() {
	*x = ListRoadsResponse{}
	mi := &file_roads_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoadsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoadsResponse) ProtoMessage() {}

func (x *ListRoadsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_roads_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoadsResponse.ProtoReflect.Descriptor instead.
func (*ListRoadsResponse) Descriptor() ([]byte, []int) {
	return file_roads_proto_rawDescGZIP(), []int{4}
}

func (x *ListRoadsResponse) GetRoads() []*Road {
	if x != nil {
		return x.Roads
	}
	return nil
}

func (x *ListRoadsResponse) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

type GetRoadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Road          *Road                  `protobuf:"bytes,1,opt,name=road,proto3" json:"road,omitempty"`
	LastUpdated   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoadResponse) Reset() {
	*x = GetRoadResponse{}
	mi := &file_roads_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoadResponse) ProtoMessage() {}

func (x *GetRoadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_roads_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoadResponse.ProtoReflect.Descriptor instead.
func (*GetRoadResponse) Descriptor() ([]byte, []int) {
	return file_roads_proto_rawDescGZIP(), []int{5}
}

func (x *GetRoadResponse) GetRoad() *Road {
	if x != nil {
		return x.Road
	}
	return nil
}

func (x *GetRoadResponse) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

type ListIncidentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Incidents     []*Incident            `protobuf:"bytes,1,rep,name=incidents,proto3" json:"incidents,omitempty"`
	LastUpdated   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	Area          string                 `protobuf:"bytes,3,opt,name=area,proto3" json:"area,omitempty"` // Echoes the resolved area id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIncidentsResponse) Reset() {
	*x = ListIncidentsResponse{}
	mi := &file_roads_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIncidentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIncidentsResponse) ProtoMessage() {}

func (x *ListIncidentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_roads_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIncidentsResponse.ProtoReflect.Descriptor instead.
func (*ListIncidentsResponse) Descriptor() ([]byte, []int) {
	return file_roads_proto_rawDescGZIP(), []int{6}
}

func (x *ListIncidentsResponse) GetIncidents() []*Incident {
	if x != nil {
		return x.Incidents
	}
	return nil
}

func (x *ListIncidentsResponse) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

func (x *ListIncidentsResponse) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

// Incident is a region-wide CHP/Caltrans dispatch incident, surfaced
// independently of any monitored road.
type Incident struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                              // Stable id (CHP log number when available)
	Type                AlertType              `protobuf:"varint,2,opt,name=type,proto3,enum=api.v1.AlertType" json:"type,omitempty"`                                   // INCIDENT, CLOSURE, CONSTRUCTION
	Severity            AlertSeverity          `protobuf:"varint,3,opt,name=severity,proto3,enum=api.v1.AlertSeverity" json:"severity,omitempty"`                       // Heuristic severity from incident text
	Location            *Coordinates           `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`                                                  // Point location
	LocationDescription string                 `protobuf:"bytes,5,opt,name=location_description,json=locationDescription,proto3" json:"location_description,omitempty"` // Human-readable location (e.g. "Sr132 Ofr / I580 E")
	Description         string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`                                            // Incident detail text (AI-enhanced for high-severity incidents)
	Status              IncidentStatus         `protobuf:"varint,7,opt,name=status,proto3,enum=api.v1.IncidentStatus" json:"status,omitempty"`                          // Lifecycle state (feeds only list active incidents)
	LogNumber           string                 `protobuf:"bytes,8,opt,name=log_number,json=logNumber,proto3" json:"log_number,omitempty"`                               // CHP/CAD log number (e.g. "250916ST0066")
	Started             *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=started,proto3" json:"started,omitempty"`                                                    // When the incident was first reported
	LastUpdated         *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`                        // Last update from the feed
	Area                string                 `protobuf:"bytes,11,opt,name=area,proto3" json:"area,omitempty"`                                                         // Area id this incident was matched to
	// AI-enhancement fields, populated only for high-severity (CRITICAL)
	// incidents — fires, injury collisions, overturns, full closures. Other
	// incidents keep the structural fields above and leave these empty/unset.
	CondensedSummary string            `protobuf:"bytes,12,opt,name=condensed_summary,json=condensedSummary,proto3" json:"condensed_summary,omitempty"`                                   // Short format for mobile
	Impact           AlertImpact       `protobuf:"varint,13,opt,name=impact,proto3,enum=api.v1.AlertImpact" json:"impact,omitempty"`                                                      // AI-assessed impact (IMPACT_UNSPECIFIED when not enhanced)
	Metadata         map[string]string `protobuf:"bytes,14,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Structured extras (vehicles involved, injuries, ...)
	// Verbatim upstream text, before any AI enhancement (CHP radio codes /
	// abbreviations). Preserved so a client can show the original alongside the
	// enhanced text — the "translate, never assert" transparency contract
	// (spec §3.1). Always set; `description` may be an AI narrative.
	OriginalText string `protobuf:"bytes,15,opt,name=original_text,json=originalText,proto3" json:"original_text,omitempty"`
	// The AI enhancement I/O (transparency): `ai_request` is the incident-specific
	// user prompt sent to the model; `ai_response` is the raw structured JSON it
	// returned. Empty when the incident was not AI-enhanced.
	AiRequest  string `protobuf:"bytes,16,opt,name=ai_request,json=aiRequest,proto3" json:"ai_request,omitempty"`
	AiResponse string `protobuf:"bytes,17,opt,name=ai_response,json=aiResponse,proto3" json:"ai_response,omitempty"`
	// When the enhancement was produced (the model run, not this fetch — cached
	// enhancements keep their original time). Unset when not AI-enhanced.
	AiEnhancedAt  *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=ai_enhanced_at,json=aiEnhancedAt,proto3" json:"ai_enhanced_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Incident) Reset() {
	*x = Incident{}
	mi := &file_roads_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Incident) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Incident) ProtoMessage() {}

func (x *Incident) ProtoReflect() protoreflect.Message {
	mi := &file_roads_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Incident.ProtoReflect.Descriptor instead.
func (*Incident) Descriptor() ([]byte, []int) {
	return file_roads_proto_rawDescGZIP(), []int{7}
}

func (x *Incident) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Incident) GetType() AlertType {
	if x != nil {
		return x.Type
	}
	return AlertType_ALERT_TYPE_UNSPECIFIED
}

func (x *Incident) GetSeverity() AlertSeverity {
	if x != nil {
		return x.Severity
	}
	return AlertSeverity_ALERT_SEVERITY_UNSPECIFIED
}

func (x *Incident) GetLocation() *Coordinates {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Incident) GetLocationDescription() string {
	if x != nil {
		return x.LocationDescription
	}
	return ""
}

func (x *Incident) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Incident) GetStatus() IncidentStatus {
	if x != nil {
		return x.Status
	}
	return IncidentStatus_INCIDENT_STATUS_UNSPECIFIED
}

func (x *Incident) GetLogNumber() string {
	if x != nil {
		return x.LogNumber
	}
	return ""
}

func (x *Incident) GetStarted() *timestamppb.Timestamp {
	if x != nil {
		return x.Started
	}
	return nil
}

func (x *Incident) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

func (x *Incident) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

func (x *Incident) GetCondensedSummary() string {
	if x != nil {
		return x.CondensedSummary
	}
	return ""
}

func (x *Incident) GetImpact() AlertImpact {
	if x != nil {
		return x.Impact
	}
	return AlertImpact_ALERT_IMPACT_UNSPECIFIED
}

func (x *Incident) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Incident) GetOriginalText() string {
	if x != nil {
		return x.OriginalText
	}
	return ""
}

func (x *Incident) GetAiRequest() string {
	if x != nil {
		return x.AiRequest
	}
	return ""
}

func (x *Incident) GetAiResponse() string {
	if x != nil {
		return x.AiResponse
	}
	return ""
}

func (x *Incident) GetAiEnhancedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AiEnhancedAt
	}
	return nil
}

type ProcessingMetrics struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TotalRawAlerts      int64                  `protobuf:"varint,1,opt,name=total_raw_alerts,json=totalRawAlerts,proto3" json:"total_raw_alerts,omitempty"`
	FilteredAlerts      int64                  `protobuf:"varint,2,opt,name=filtered_alerts,json=filteredAlerts,proto3" json:"filtered_alerts,omitempty"`
	EnhancedAlerts      int64                  `protobuf:"varint,3,opt,name=enhanced_alerts,json=enhancedAlerts,proto3" json:"enhanced_alerts,omitempty"`
	EnhancementFailures int64                  `protobuf:"varint,4,opt,name=enhancement_failures,json=enhancementFailures,proto3" json:"enhancement_failures,omitempty"`
	AvgProcessingTimeMs float64                `protobuf:"fixed64,5,opt,name=avg_processing_time_ms,json=avgProcessingTimeMs,proto3" json:"avg_processing_time_ms,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ProcessingMetrics) Reset() {
	*x = ProcessingMetrics{}
	mi := &file_roads_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessingMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessingMetrics) ProtoMessage() {}

func (x *ProcessingMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_roads_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessingMetrics.ProtoReflect.Descriptor instead.
func (*ProcessingMetrics) Descriptor() ([]byte, []int) {
	return file_roads_proto_rawDescGZIP(), []int{8}
}

func (x *ProcessingMetrics) GetTotalRawAlerts() int64 {
	if x != nil {
		return x.TotalRawAlerts
	}
	return 0
}

func (x *ProcessingMetrics) GetFilteredAlerts() int64 {
	if x != nil {
		return x.FilteredAlerts
	}
	return 0
}

func (x *ProcessingMetrics) GetEnhancedAlerts() int64 {
	if x != nil {
		return x.EnhancedAlerts
	}
	return 0
}

func (x *ProcessingMetrics) GetEnhancementFailures() int64 {
	if x != nil {
		return x.EnhancementFailures
	}
	return 0
}

func (x *ProcessingMetrics) GetAvgProcessingTimeMs() float64 {
	if x != nil {
		return x.AvgProcessingTimeMs
	}
	return 0
}

// Data models
type Road struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                                           // Highway/road name (e.g., "Hwy 4")
	Section           string                 `protobuf:"bytes,3,opt,name=section,proto3" json:"section,omitempty"`                                                                     // Section description (e.g., "Arnold to Bear Valley")
	Status            RoadStatus             `protobuf:"varint,4,opt,name=status,proto3,enum=api.v1.RoadStatus" json:"status,omitempty"`                                               // Current road status
	StatusExplanation string                 `protobuf:"bytes,5,opt,name=status_explanation,json=statusExplanation,proto3" json:"status_explanation,omitempty"`                        // Explanation when status is RESTRICTED or CLOSED
	DurationMinutes   int32                  `protobuf:"varint,6,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`                             // Current travel time in minutes
	DistanceKm        int32                  `protobuf:"varint,7,opt,name=distance_km,json=distanceKm,proto3" json:"distance_km,omitempty"`                                            // Route distance in kilometers
	CongestionLevel   CongestionLevel        `protobuf:"varint,8,opt,name=congestion_level,json=congestionLevel,proto3,enum=api.v1.CongestionLevel" json:"congestion_level,omitempty"` // Traffic congestion level
	DelayMinutes      int32                  `protobuf:"varint,9,opt,name=delay_minutes,json=delayMinutes,proto3" json:"delay_minutes,omitempty"`                                      // Additional time due to traffic (0 = no delays)
	ChainControl      ChainControlStatus     `protobuf:"varint,10,opt,name=chain_control,json=chainControl,proto3,enum=api.v1.ChainControlStatus" json:"chain_control,omitempty"`      // Chain control requirements (legacy, use chain_control_info)
	Alerts            []*RoadAlert           `protobuf:"bytes,11,rep,name=alerts,proto3" json:"alerts,omitempty"`                                                                      // Combined from multiple sources
	ChainControlInfo  *ChainControlInfo      `protobuf:"bytes,12,opt,name=chain_control_info,json=chainControlInfo,proto3" json:"chain_control_info,omitempty"`                        // Detailed chain control information
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Road) Reset() {
	*x = Road{}
	mi := &file_roads_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Road) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Road) ProtoMessage() {}

func (x *Road) ProtoReflect() protoreflect.Message {
	mi := &file_roads_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Road.ProtoReflect.Descriptor instead.
func (*Road) Descriptor() ([]byte, []int) {
	return file_roads_proto_rawDescGZIP(), []int{9}
}

func (x *Road) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Road) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Road) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

func (x *Road) GetStatus() RoadStatus {
	if x != nil {
		return x.Status
	}
	return RoadStatus_ROAD_STATUS_UNSPECIFIED
}

func (x *Road) GetStatusExplanation() string {
	if x != nil {
		return x.StatusExplanation
	}
	return ""
}

func (x *Road) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

func (x *Road) GetDistanceKm() int32 {
	if x != nil {
		return x.DistanceKm
	}
	return 0
}

func (x *Road) GetCongestionLevel() CongestionLevel {
	if x != nil {
		return x.CongestionLevel
	}
	return CongestionLevel_CONGESTION_LEVEL_UNSPECIFIED
}

func (x *Road) GetDelayMinutes() int32 {
	if x != nil {
		return x.DelayMinutes
	}
	return 0
}

func (x *Road) GetChainControl() ChainControlStatus {
	if x != nil {
		return x.ChainControl
	}
	return ChainControlStatus_CHAIN_CONTROL_UNSPECIFIED
}

func (x *Road) GetAlerts() []*RoadAlert {
	if x != nil {
		return x.Alerts
	}
	return nil
}

func (x *Road) GetChainControlInfo() *ChainControlInfo {
	if x != nil {
		return x.ChainControlInfo
	}
	return nil
}

// ChainControlInfo provides detailed chain control status for a road
type ChainControlInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         ChainControlLevel      `protobuf:"varint,1,opt,name=level,proto3,enum=api.v1.ChainControlLevel" json:"level,omitempty"`       // R1, R2, or NONE
	LocationName  string                 `protobuf:"bytes,2,opt,name=location_name,json=locationName,proto3" json:"location_name,omitempty"`    // Where chain control starts (e.g., "Twin Bridges")
	Latitude      float64                `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`                              // Latitude of chain control checkpoint
	Longitude     float64                `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`                            // Longitude of chain control checkpoint
	EffectiveTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=effective_time,json=effectiveTime,proto3" json:"effective_time,omitempty"` // When chain control went into effect
	Direction     string                 `protobuf:"bytes,6,opt,name=direction,proto3" json:"direction,omitempty"`                              // Direction of travel (e.g., "Eastbound")
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`                          // Human-readable requirements description
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainControlInfo) Reset() {
	*x = ChainControlInfo{}
	mi := &file_roads_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainControlInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainControlInfo) ProtoMessage() {}

func (x *ChainControlInfo) ProtoReflect() protoreflect.Message {
	mi := &file_roads_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainControlInfo.ProtoReflect.Descriptor instead.
func (*ChainControlInfo) Descriptor() ([]byte, []int) {
	return file_roads_proto_rawDescGZIP(), []int{10}
}

func (x *ChainControlInfo) GetLevel() ChainControlLevel {
	if x != nil {
		return x.Level
	}
	return ChainControlLevel_CHAIN_CONTROL_LEVEL_UNSPECIFIED
}

func (x *ChainControlInfo) GetLocationName() string {
	if x != nil {
		return x.LocationName
	}
	return ""
}

func (x *ChainControlInfo) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *ChainControlInfo) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *ChainControlInfo) GetEffectiveTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EffectiveTime
	}
	return nil
}

func (x *ChainControlInfo) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *ChainControlInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type RoadAlert struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Type                  AlertType              `protobuf:"varint,1,opt,name=type,proto3,enum=api.v1.AlertType" json:"type,omitempty"`
	Severity              AlertSeverity          `protobuf:"varint,2,opt,name=severity,proto3,enum=api.v1.AlertSeverity" json:"severity,omitempty"`
	Classification        AlertClassification    `protobuf:"varint,3,opt,name=classification,proto3,enum=api.v1.AlertClassification" json:"classification,omitempty"` // On route vs nearby vs distant
	Title                 string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`                                                    // Actual Caltrans title (e.g., "CHP Incident 250911GG0206")
	Description           string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`                                        // AI-processed description
	CondensedSummary      string                 `protobuf:"bytes,6,opt,name=condensed_summary,json=condensedSummary,proto3" json:"condensed_summary,omitempty"`      // Short format for mobile
	StartTime             *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime               *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	LastUpdated           *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	Location              *Coordinates           `protobuf:"bytes,10,opt,name=location,proto3" json:"location,omitempty"`                                                                           // Structured location with lat/lon
	LocationDescription   string                 `protobuf:"bytes,11,opt,name=location_description,json=locationDescription,proto3" json:"location_description,omitempty"`                          // Human-friendly location description
	Impact                AlertImpact            `protobuf:"varint,12,opt,name=impact,proto3,enum=api.v1.AlertImpact" json:"impact,omitempty"`                                                      // AI-assessed impact
	Duration              AlertDuration          `protobuf:"varint,13,opt,name=duration,proto3,enum=api.v1.AlertDuration" json:"duration,omitempty"`                                                // AI-assessed duration
	TimeReported          *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=time_reported,json=timeReported,proto3" json:"time_reported,omitempty"`                                               // When incident was first reported
	Metadata              map[string]string      `protobuf:"bytes,15,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional AI-generated key-value pairs only
	DistanceToRouteMeters float64                `protobuf:"fixed64,16,opt,name=distance_to_route_meters,json=distanceToRouteMeters,proto3" json:"distance_to_route_meters,omitempty"`              // Distance from alert location to route in meters (for NEARBY alerts)
	Id                    string                 `protobuf:"bytes,17,opt,name=id,proto3" json:"id,omitempty"`                                                                                       // Stable CHP log / closure id; matches Incident.id for the same event (empty if none)
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RoadAlert) Reset() {
	*x = RoadAlert{}
	mi := &file_roads_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoadAlert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoadAlert) ProtoMessage() {}

func (x *RoadAlert) ProtoReflect() protoreflect.Message {
	mi := &file_roads_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoadAlert.ProtoReflect.Descriptor instead.
func (*RoadAlert) Descriptor() ([]byte, []int) {
	return file_roads_proto_rawDescGZIP(), []int{11}
}

func (x *RoadAlert) GetType() AlertType {
	if x != nil {
		return x.Type
	}
	return AlertType_ALERT_TYPE_UNSPECIFIED
}

func (x *RoadAlert) GetSeverity() AlertSeverity {
	if x != nil {
		return x.Severity
	}
	return AlertSeverity_ALERT_SEVERITY_UNSPECIFIED
}

func (x *RoadAlert) GetClassification() AlertClassification {
	if x != nil {
		return x.Classification
	}
	return AlertClassification_ALERT_CLASSIFICATION_UNSPECIFIED
}

func (x *RoadAlert) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RoadAlert) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RoadAlert) GetCondensedSummary() string {
	if x != nil {
		return x.CondensedSummary
	}
	return ""
}

func (x *RoadAlert) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *RoadAlert) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *RoadAlert) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

func (x *RoadAlert) GetLocation() *Coordinates {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *RoadAlert) GetLocationDescription() string {
	if x != nil {
		return x.LocationDescription
	}
	return ""
}

func (x *RoadAlert) GetImpact() AlertImpact {
	if x != nil {
		return x.Impact
	}
	return AlertImpact_ALERT_IMPACT_UNSPECIFIED
}

func (x *RoadAlert) GetDuration() AlertDuration {
	if x != nil {
		return x.Duration
	}
	return AlertDuration_ALERT_DURATION_UNSPECIFIED
}

func (x *RoadAlert) GetTimeReported() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeReported
	}
	return nil
}

func (x *RoadAlert) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RoadAlert) GetDistanceToRouteMeters() float64 {
	if x != nil {
		return x.DistanceToRouteMeters
	}
	return 0
}

func (x *RoadAlert) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TrafficIncident struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description           string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	LocationMileMarker    float32                `protobuf:"fixed32,3,opt,name=location_mile_marker,json=locationMileMarker,proto3" json:"location_mile_marker,omitempty"`
	EstimatedDelayMinutes int32                  `protobuf:"varint,4,opt,name=estimated_delay_minutes,json=estimatedDelayMinutes,proto3" json:"estimated_delay_minutes,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TrafficIncident) Reset() {
	*x = TrafficIncident{}
	mi := &file_roads_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficIncident) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficIncident) ProtoMessage() {}

func (x *TrafficIncident) ProtoReflect() protoreflect.Message {
	mi := &file_roads_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficIncident.ProtoReflect.Descriptor instead.
func (*TrafficIncident) Descriptor() ([]byte, []int) {
	return file_roads_proto_rawDescGZIP(), []int{12}
}

func (x *TrafficIncident) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TrafficIncident) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TrafficIncident) GetLocationMileMarker() float32 {
	if x != nil {
		return x.LocationMileMarker
	}
	return 0
}

func (x *TrafficIncident) GetEstimatedDelayMinutes() int32 {
	if x != nil {
		return x.EstimatedDelayMinutes
	}
	return 0
}

var File_roads_proto protoreflect.FileDescriptor

const file_roads_proto_rawDesc = "" +
	"\n" +
	"\vroads.proto\x12\x06api.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\fcommon.proto\"\x12\n" +
	"\x10ListRoadsRequest\")\n" +
	"\x0eGetRoadRequest\x12\x17\n" +
	"\aroad_id\x18\x01 \x01(\tR\x06roadId\"\x1d\n" +
	"\x1bGetProcessingMetricsRequest\"*\n" +
	"\x14ListIncidentsRequest\x12\x12\n" +
	"\x04area\x18\x01 \x01(\tR\x04area\"v\n" +
	"\x11ListRoadsResponse\x12\"\n" +
	"\x05roads\x18\x01 \x03(\v2\f.api.v1.RoadR\x05roads\x12=\n" +
	"\flast_updated\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\"r\n" +
	"\x0fGetRoadResponse\x12 \n" +
	"\x04road\x18\x01 \x01(\v2\f.api.v1.RoadR\x04road\x12=\n" +
	"\flast_updated\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\"\x9a\x01\n" +
	"\x15ListIncidentsResponse\x12.\n" +
	"\tincidents\x18\x01 \x03(\v2\x10.api.v1.IncidentR\tincidents\x12=\n" +
	"\flast_updated\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\x12\x12\n" +
	"\x04area\x18\x03 \x01(\tR\x04area\"\xcc\x06\n" +
	"\bIncident\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x04type\x18\x02 \x01(\x0e2\x11.api.v1.AlertTypeR\x04type\x121\n" +
	"\bseverity\x18\x03 \x01(\x0e2\x15.api.v1.AlertSeverityR\bseverity\x12/\n" +
	"\blocation\x18\x04 \x01(\v2\x13.api.v1.CoordinatesR\blocation\x121\n" +
	"\x14location_description\x18\x05 \x01(\tR\x13locationDescription\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12.\n" +
	"\x06status\x18\a \x01(\x0e2\x16.api.v1.IncidentStatusR\x06status\x12\x1d\n" +
	"\n" +
	"log_number\x18\b \x01(\tR\tlogNumber\x124\n" +
	"\astarted\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\astarted\x12=\n" +
	"\flast_updated\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\x12\x12\n" +
	"\x04area\x18\v \x01(\tR\x04area\x12+\n" +
	"\x11condensed_summary\x18\f \x01(\tR\x10condensedSummary\x12+\n" +
	"\x06impact\x18\r \x01(\x0e2\x13.api.v1.AlertImpactR\x06impact\x12:\n" +
	"\bmetadata\x18\x0e \x03(\v2\x1e.api.v1.Incident.MetadataEntryR\bmetadata\x12#\n" +
	"\roriginal_text\x18\x0f \x01(\tR\foriginalText\x12\x1d\n" +
	"\n" +
	"ai_request\x18\x10 \x01(\tR\taiRequest\x12\x1f\n" +
	"\vai_response\x18\x11 \x01(\tR\n" +
	"aiResponse\x12@\n" +
	"\x0eai_enhanced_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\faiEnhancedAt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf7\x01\n" +
	"\x11ProcessingMetrics\x12(\n" +
	"\x10total_raw_alerts\x18\x01 \x01(\x03R\x0etotalRawAlerts\x12'\n" +
	"\x0ffiltered_alerts\x18\x02 \x01(\x03R\x0efilteredAlerts\x12'\n" +
	"\x0fenhanced_alerts\x18\x03 \x01(\x03R\x0eenhancedAlerts\x121\n" +
	"\x14enhancement_failures\x18\x04 \x01(\x03R\x13enhancementFailures\x123\n" +
	"\x16avg_processing_time_ms\x18\x05 \x01(\x01R\x13avgProcessingTimeMs\"\x88\x04\n" +
	"\x04Road\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\asection\x18\x03 \x01(\tR\asection\x12*\n" +
	"\x06status\x18\x04 \x01(\x0e2\x12.api.v1.RoadStatusR\x06status\x12-\n" +
	"\x12status_explanation\x18\x05 \x01(\tR\x11statusExplanation\x12)\n" +
	"\x10duration_minutes\x18\x06 \x01(\x05R\x0fdurationMinutes\x12\x1f\n" +
	"\vdistance_km\x18\a \x01(\x05R\n" +
	"distanceKm\x12B\n" +
	"\x10congestion_level\x18\b \x01(\x0e2\x17.api.v1.CongestionLevelR\x0fcongestionLevel\x12#\n" +
	"\rdelay_minutes\x18\t \x01(\x05R\fdelayMinutes\x12?\n" +
	"\rchain_control\x18\n" +
	" \x01(\x0e2\x1a.api.v1.ChainControlStatusR\fchainControl\x12)\n" +
	"\x06alerts\x18\v \x03(\v2\x11.api.v1.RoadAlertR\x06alerts\x12F\n" +
	"\x12chain_control_info\x18\f \x01(\v2\x18.api.v1.ChainControlInfoR\x10chainControlInfo\"\xa5\x02\n" +
	"\x10ChainControlInfo\x12/\n" +
	"\x05level\x18\x01 \x01(\x0e2\x19.api.v1.ChainControlLevelR\x05level\x12#\n" +
	"\rlocation_name\x18\x02 \x01(\tR\flocationName\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x01R\tlongitude\x12A\n" +
	"\x0eeffective_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\reffectiveTime\x12\x1c\n" +
	"\tdirection\x18\x06 \x01(\tR\tdirection\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\"\x88\a\n" +
	"\tRoadAlert\x12%\n" +
	"\x04type\x18\x01 \x01(\x0e2\x11.api.v1.AlertTypeR\x04type\x121\n" +
	"\bseverity\x18\x02 \x01(\x0e2\x15.api.v1.AlertSeverityR\bseverity\x12C\n" +
	"\x0eclassification\x18\x03 \x01(\x0e2\x1b.api.v1.AlertClassificationR\x0eclassification\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12+\n" +
	"\x11condensed_summary\x18\x06 \x01(\tR\x10condensedSummary\x129\n" +
	"\n" +
	"start_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12=\n" +
	"\flast_updated\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\x12/\n" +
	"\blocation\x18\n" +
	" \x01(\v2\x13.api.v1.CoordinatesR\blocation\x121\n" +
	"\x14location_description\x18\v \x01(\tR\x13locationDescription\x12+\n" +
	"\x06impact\x18\f \x01(\x0e2\x13.api.v1.AlertImpactR\x06impact\x121\n" +
	"\bduration\x18\r \x01(\x0e2\x15.api.v1.AlertDurationR\bduration\x12?\n" +
	"\rtime_reported\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\ftimeReported\x12;\n" +
	"\bmetadata\x18\x0f \x03(\v2\x1f.api.v1.RoadAlert.MetadataEntryR\bmetadata\x127\n" +
	"\x18distance_to_route_meters\x18\x10 \x01(\x01R\x15distanceToRouteMeters\x12\x0e\n" +
	"\x02id\x18\x11 \x01(\tR\x02id\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xad\x01\n" +
	"\x0fTrafficIncident\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x120\n" +
	"\x14location_mile_marker\x18\x03 \x01(\x02R\x12locationMileMarker\x126\n" +
	"\x17estimated_delay_minutes\x18\x04 \x01(\x05R\x15estimatedDelayMinutes*`\n" +
	"\n" +
	"RoadStatus\x12\x1b\n" +
	"\x17ROAD_STATUS_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04OPEN\x10\x01\x12\n" +
	"\n" +
	"\x06CLOSED\x10\x02\x12\x0e\n" +
	"\n" +
	"RESTRICTED\x10\x03\x12\x0f\n" +
	"\vMAINTENANCE\x10\x04*h\n" +
	"\x12ChainControlStatus\x12\x1d\n" +
	"\x19CHAIN_CONTROL_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04NONE\x10\x01\x12\v\n" +
	"\aADVISED\x10\x02\x12\f\n" +
	"\bREQUIRED\x10\x03\x12\x0e\n" +
	"\n" +
	"PROHIBITED\x10\x04*\xaa\x01\n" +
	"\x11ChainControlLevel\x12#\n" +
	"\x1fCHAIN_CONTROL_LEVEL_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18CHAIN_CONTROL_LEVEL_NONE\x10\x01\x12\x1a\n" +
	"\x16CHAIN_CONTROL_LEVEL_R1\x10\x02\x12\x1a\n" +
	"\x16CHAIN_CONTROL_LEVEL_R2\x10\x03\x12\x1a\n" +
	"\x16CHAIN_CONTROL_LEVEL_R3\x10\x04*n\n" +
	"\x0fCongestionLevel\x12 \n" +
	"\x1cCONGESTION_LEVEL_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05CLEAR\x10\x01\x12\t\n" +
	"\x05LIGHT\x10\x02\x12\f\n" +
	"\bMODERATE\x10\x03\x12\t\n" +
	"\x05HEAVY\x10\x04\x12\n" +
	"\n" +
	"\x06SEVERE\x10\x05*a\n" +
	"\tAlertType\x12\x1a\n" +
	"\x16ALERT_TYPE_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aCLOSURE\x10\x01\x12\x10\n" +
	"\fCONSTRUCTION\x10\x02\x12\f\n" +
	"\bINCIDENT\x10\x03\x12\v\n" +
	"\aWEATHER\x10\x04*b\n" +
	"\x13AlertClassification\x12$\n" +
	" ALERT_CLASSIFICATION_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bON_ROUTE\x10\x01\x12\n" +
	"\n" +
	"\x06NEARBY\x10\x02\x12\v\n" +
	"\aDISTANT\x10\x032\xa5\x03\n" +
	"\fRoadsService\x12W\n" +
	"\tListRoads\x12\x18.api.v1.ListRoadsRequest\x1a\x19.api.v1.ListRoadsResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/api/v1/roads\x12[\n" +
	"\aGetRoad\x12\x16.api.v1.GetRoadRequest\x1a\x17.api.v1.GetRoadResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/api/v1/roads/{road_id}\x12o\n" +
	"\x14GetProcessingMetrics\x12#.api.v1.GetProcessingMetricsRequest\x1a\x19.api.v1.ProcessingMetrics\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/api/v1/metrics\x12n\n" +
	"\rListIncidents\x12\x1c.api.v1.ListIncidentsRequest\x1a\x1d.api.v1.ListIncidentsResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/v1/incidents/{area}B\xb1\x02\x92A\x80\x02\x12\x8f\x01\n" +
	"\x0eERSN Roads API\x12MReal-time road conditions and traffic information for the Ebbetts Pass region\")\n" +
	"\x10ERSN Info Server\x12\x15https://info.ersn.net2\x031.0*\x02\x02\x012\x10application/json:\x10application/jsonrD\n" +
	"\x1bMore about ERSN Info Server\x12%https://github.com/dpup/info.ersn.netZ+github.com/dpup/info.ersn.net/server/api/v1b\x06proto3"

var (
	file_roads_proto_rawDescOnce sync.Once
	file_roads_proto_rawDescData []byte
)

func file_roads_proto_rawDescGZIP() []byte {
	file_roads_proto_rawDescOnce.Do(func() {
		file_roads_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_roads_proto_rawDesc), len(file_roads_proto_rawDesc)))
	})
	return file_roads_proto_rawDescData
}

var file_roads_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_roads_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_roads_proto_goTypes = []any{
	(RoadStatus)(0),                     // 0: api.v1.RoadStatus
	(ChainControlStatus)(0),             // 1: api.v1.ChainControlStatus
	(ChainControlLevel)(0),              // 2: api.v1.ChainControlLevel
	(CongestionLevel)(0),                // 3: api.v1.CongestionLevel
	(AlertType)(0),                      // 4: api.v1.AlertType
	(AlertClassification)(0),            // 5: api.v1.AlertClassification
	(*ListRoadsRequest)(nil),            // 6: api.v1.ListRoadsRequest
	(*GetRoadRequest)(nil),              // 7: api.v1.GetRoadRequest
	(*GetProcessingMetricsRequest)(nil), // 8: api.v1.GetProcessingMetricsRequest
	(*ListIncidentsRequest)(nil),        // 9: api.v1.ListIncidentsRequest
	(*ListRoadsResponse)(nil),           // 10: api.v1.ListRoadsResponse
	(*GetRoadResponse)(nil),             // 11: api.v1.GetRoadResponse
	(*ListIncidentsResponse)(nil),       // 12: api.v1.ListIncidentsResponse
	(*Incident)(nil),                    // 13: api.v1.Incident
	(*ProcessingMetrics)(nil),           // 14: api.v1.ProcessingMetrics
	(*Road)(nil),                        // 15: api.v1.Road
	(*ChainControlInfo)(nil),            // 16: api.v1.ChainControlInfo
	(*RoadAlert)(nil),                   // 17: api.v1.RoadAlert
	(*TrafficIncident)(nil),             // 18: api.v1.TrafficIncident
	nil,                                 // 19: api.v1.Incident.MetadataEntry
	nil,                                 // 20: api.v1.RoadAlert.MetadataEntry
	(*timestamppb.Timestamp)(nil),       // 21: google.protobuf.Timestamp
	(AlertSeverity)(0),                  // 22: api.v1.AlertSeverity
	(*Coordinates)(nil),                 // 23: api.v1.Coordinates
	(IncidentStatus)(0),                 // 24: api.v1.IncidentStatus
	(AlertImpact)(0),                    // 25: api.v1.AlertImpact
	(AlertDuration)(0),                  // 26: api.v1.AlertDuration
}
var file_roads_proto_depIdxs = []int32{
	15, // 0: api.v1.ListRoadsResponse.roads:type_name -> api.v1.Road
	21, // 1: api.v1.ListRoadsResponse.last_updated:type_name -> google.protobuf.Timestamp
	15, // 2: api.v1.GetRoadResponse.road:type_name -> api.v1.Road
	21, // 3: api.v1.GetRoadResponse.last_updated:type_name -> google.protobuf.Timestamp
	13, // 4: api.v1.ListIncidentsResponse.incidents:type_name -> api.v1.Incident
	21, // 5: api.v1.ListIncidentsResponse.last_updated:type_name -> google.protobuf.Timestamp
	4,  // 6: api.v1.Incident.type:type_name -> api.v1.AlertType
	22, // 7: api.v1.Incident.severity:type_name -> api.v1.AlertSeverity
	23, // 8: api.v1.Incident.location:type_name -> api.v1.Coordinates
	24, // 9: api.v1.Incident.status:type_name -> api.v1.IncidentStatus
	21, // 10: api.v1.Incident.started:type_name -> google.protobuf.Timestamp
	21, // 11: api.v1.Incident.last_updated:type_name -> google.protobuf.Timestamp
	25, // 12: api.v1.Incident.impact:type_name -> api.v1.AlertImpact
	19, // 13: api.v1.Incident.metadata:type_name -> api.v1.Incident.MetadataEntry
	21, // 14: api.v1.Incident.ai_enhanced_at:type_name -> google.protobuf.Timestamp
	0,  // 15: api.v1.Road.status:type_name -> api.v1.RoadStatus
	3,  // 16: api.v1.Road.congestion_level:type_name -> api.v1.CongestionLevel
	1,  // 17: api.v1.Road.chain_control:type_name -> api.v1.ChainControlStatus
	17, // 18: api.v1.Road.alerts:type_name -> api.v1.RoadAlert
	16, // 19: api.v1.Road.chain_control_info:type_name -> api.v1.ChainControlInfo
	2,  // 20: api.v1.ChainControlInfo.level:type_name -> api.v1.ChainControlLevel
	21, // 21: api.v1.ChainControlInfo.effective_time:type_name -> google.protobuf.Timestamp
	4,  // 22: api.v1.RoadAlert.type:type_name -> api.v1.AlertType
	22, // 23: api.v1.RoadAlert.severity:type_name -> api.v1.AlertSeverity
	5,  // 24: api.v1.RoadAlert.classification:type_name -> api.v1.AlertClassification
	21, // 25: api.v1.RoadAlert.start_time:type_name -> google.protobuf.Timestamp
	21, // 26: api.v1.RoadAlert.end_time:type_name -> google.protobuf.Timestamp
	21, // 27: api.v1.RoadAlert.last_updated:type_name -> google.protobuf.Timestamp
	23, // 28: api.v1.RoadAlert.location:type_name -> api.v1.Coordinates
	25, // 29: api.v1.RoadAlert.impact:type_name -> api.v1.AlertImpact
	26, // 30: api.v1.RoadAlert.duration:type_name -> api.v1.AlertDuration
	21, // 31: api.v1.RoadAlert.time_reported:type_name -> google.protobuf.Timestamp
	20, // 32: api.v1.RoadAlert.metadata:type_name -> api.v1.RoadAlert.MetadataEntry
	6,  // 33: api.v1.RoadsService.ListRoads:input_type -> api.v1.ListRoadsRequest
	7,  // 34: api.v1.RoadsService.GetRoad:input_type -> api.v1.GetRoadRequest
	8,  // 35: api.v1.RoadsService.GetProcessingMetrics:input_type -> api.v1.GetProcessingMetricsRequest
	9,  // 36: api.v1.RoadsService.ListIncidents:input_type -> api.v1.ListIncidentsRequest
	10, // 37: api.v1.RoadsService.ListRoads:output_type -> api.v1.ListRoadsResponse
	11, // 38: api.v1.RoadsService.GetRoad:output_type -> api.v1.GetRoadResponse
	14, // 39: api.v1.RoadsService.GetProcessingMetrics:output_type -> api.v1.ProcessingMetrics
	12, // 40: api.v1.RoadsService.ListIncidents:output_type -> api.v1.ListIncidentsResponse
	37, // [37:41] is the sub-list for method output_type
	33, // [33:37] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_roads_proto_init() }
func file_roads_proto_init() {
	if File_roads_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_roads_proto_rawDesc), len(file_roads_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_roads_proto_goTypes,
		DependencyIndexes: file_roads_proto_depIdxs,
		EnumInfos:         file_roads_proto_enumTypes,
		MessageInfos:      file_roads_proto_msgTypes,
	}.Build()
	File_roads_proto = out.File
	file_roads_proto_goTypes = nil
	file_roads_proto_depIdxs = nil
}
