// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.33.1
// source: weather.proto

package v1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request messages
type ListWeatherRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWeatherRequest) Reset() {
	*x = ListWeatherRequest{}
	mi := &file_weather_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWeatherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWeatherRequest) ProtoMessage() {}

func (x *ListWeatherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_weather_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWeatherRequest.ProtoReflect.Descriptor instead.
func (*ListWeatherRequest) Descriptor() ([]byte, []int) {
	return file_weather_proto_rawDescGZIP(), []int{0}
}

type GetLocationWeatherRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocationId    string                 `protobuf:"bytes,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLocationWeatherRequest) Reset() {
	*x = GetLocationWeatherRequest{}
	mi := &file_weather_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLocationWeatherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocationWeatherRequest) ProtoMessage() {}

func (x *GetLocationWeatherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_weather_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocationWeatherRequest.ProtoReflect.Descriptor instead.
func (*GetLocationWeatherRequest) Descriptor() ([]byte, []int) {
	return file_weather_proto_rawDescGZIP(), []int{1}
}

func (x *GetLocationWeatherRequest) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

type ListWeatherAlertsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional NWS forecast zone filter (e.g. "CAZ064"). When provided, NWS alerts
	// are narrowed to these zones; non-NWS alerts (OpenWeatherMap) are not
	// zone-scoped and are unaffected. Repeat the param (?zones=CAZ064&zones=CAZ065)
	// or pass a comma-separated value.
	Zones         []string `protobuf:"bytes,1,rep,name=zones,proto3" json:"zones,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWeatherAlertsRequest) Reset() {
	*x = ListWeatherAlertsRequest{}
	mi := &file_weather_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWeatherAlertsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWeatherAlertsRequest) ProtoMessage() {}

func (x *ListWeatherAlertsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_weather_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWeatherAlertsRequest.ProtoReflect.Descriptor instead.
func (*ListWeatherAlertsRequest) Descriptor() ([]byte, []int) {
	return file_weather_proto_rawDescGZIP(), []int{2}
}

func (x *ListWeatherAlertsRequest) GetZones() []string {
	if x != nil {
		return x.Zones
	}
	return nil
}

// Response messages
type ListWeatherResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WeatherData   []*WeatherData         `protobuf:"bytes,1,rep,name=weather_data,json=weatherData,proto3" json:"weather_data,omitempty"`
	LastUpdated   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	FireWeather   *FireWeather           `protobuf:"bytes,3,opt,name=fire_weather,json=fireWeather,proto3" json:"fire_weather,omitempty"` // Region-wide fire-weather classification (NWS-derived)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWeatherResponse) Reset() {
	*x = ListWeatherResponse{}
	mi := &file_weather_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWeatherResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWeatherResponse) ProtoMessage() {}

func (x *ListWeatherResponse) ProtoReflect() protoreflect.Message {
	mi := &file_weather_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWeatherResponse.ProtoReflect.Descriptor instead.
func (*ListWeatherResponse) Descriptor() ([]byte, []int) {
	return file_weather_proto_rawDescGZIP(), []int{3}
}

func (x *ListWeatherResponse) GetWeatherData() []*WeatherData {
	if x != nil {
		return x.WeatherData
	}
	return nil
}

func (x *ListWeatherResponse) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

func (x *ListWeatherResponse) GetFireWeather() *FireWeather {
	if x != nil {
		return x.FireWeather
	}
	return nil
}

type GetLocationWeatherResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WeatherData   *WeatherData           `protobuf:"bytes,1,opt,name=weather_data,json=weatherData,proto3" json:"weather_data,omitempty"`
	LastUpdated   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	FireWeather   *FireWeather           `protobuf:"bytes,3,opt,name=fire_weather,json=fireWeather,proto3" json:"fire_weather,omitempty"` // Region-wide fire-weather classification (NWS-derived)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLocationWeatherResponse) Reset() {
	*x = GetLocationWeatherResponse{}
	mi := &file_weather_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLocationWeatherResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocationWeatherResponse) ProtoMessage() {}

func (x *GetLocationWeatherResponse) ProtoReflect() protoreflect.Message {
	mi := &file_weather_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocationWeatherResponse.ProtoReflect.Descriptor instead.
func (*GetLocationWeatherResponse) Descriptor() ([]byte, []int) {
	return file_weather_proto_rawDescGZIP(), []int{4}
}

func (x *GetLocationWeatherResponse) GetWeatherData() *WeatherData {
	if x != nil {
		return x.WeatherData
	}
	return nil
}

func (x *GetLocationWeatherResponse) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

func (x *GetLocationWeatherResponse) GetFireWeather() *FireWeather {
	if x != nil {
		return x.FireWeather
	}
	return nil
}

type ListWeatherAlertsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alerts        []*WeatherAlert        `protobuf:"bytes,1,rep,name=alerts,proto3" json:"alerts,omitempty"`
	LastUpdated   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWeatherAlertsResponse) Reset() {
	*x = ListWeatherAlertsResponse{}
	mi := &file_weather_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWeatherAlertsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWeatherAlertsResponse) ProtoMessage() {}

func (x *ListWeatherAlertsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_weather_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWeatherAlertsResponse.ProtoReflect.Descriptor instead.
func (*ListWeatherAlertsResponse) Descriptor() ([]byte, []int) {
	return file_weather_proto_rawDescGZIP(), []int{5}
}

func (x *ListWeatherAlertsResponse) GetAlerts() []*WeatherAlert {
	if x != nil {
		return x.Alerts
	}
	return nil
}

func (x *ListWeatherAlertsResponse) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

// Data models
type WeatherData struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	LocationId           string                 `protobuf:"bytes,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	LocationName         string                 `protobuf:"bytes,2,opt,name=location_name,json=locationName,proto3" json:"location_name,omitempty"`
	WeatherMain          string                 `protobuf:"bytes,3,opt,name=weather_main,json=weatherMain,proto3" json:"weather_main,omitempty"`                                // "Clear", "Rain", "Snow", etc.
	WeatherDescription   string                 `protobuf:"bytes,4,opt,name=weather_description,json=weatherDescription,proto3" json:"weather_description,omitempty"`           // "light rain", "clear sky", etc.
	WeatherIcon          string                 `protobuf:"bytes,5,opt,name=weather_icon,json=weatherIcon,proto3" json:"weather_icon,omitempty"`                                // Icon code for display
	TemperatureCelsius   int32                  `protobuf:"varint,6,opt,name=temperature_celsius,json=temperatureCelsius,proto3" json:"temperature_celsius,omitempty"`          // Temperature in Celsius (rounded)
	FeelsLikeCelsius     int32                  `protobuf:"varint,7,opt,name=feels_like_celsius,json=feelsLikeCelsius,proto3" json:"feels_like_celsius,omitempty"`              // Feels like temperature in Celsius (rounded)
	HumidityPercent      int32                  `protobuf:"varint,8,opt,name=humidity_percent,json=humidityPercent,proto3" json:"humidity_percent,omitempty"`                   // Humidity percentage (0-100)
	WindSpeedKmh         int32                  `protobuf:"varint,9,opt,name=wind_speed_kmh,json=windSpeedKmh,proto3" json:"wind_speed_kmh,omitempty"`                          // Wind speed in km/h (more user-friendly)
	WindDirectionDegrees int32                  `protobuf:"varint,10,opt,name=wind_direction_degrees,json=windDirectionDegrees,proto3" json:"wind_direction_degrees,omitempty"` // Wind direction in degrees (0-360)
	VisibilityKm         int32                  `protobuf:"varint,11,opt,name=visibility_km,json=visibilityKm,proto3" json:"visibility_km,omitempty"`                           // Visibility distance in kilometers
	Alerts               []*WeatherAlert        `protobuf:"bytes,12,rep,name=alerts,proto3" json:"alerts,omitempty"`                                                            // Active weather alerts
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *WeatherData) Reset() {
	*x = WeatherData{}
	mi := &file_weather_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeatherData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeatherData) ProtoMessage() {}

func (x *WeatherData) ProtoReflect() protoreflect.Message {
	mi := &file_weather_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeatherData.ProtoReflect.Descriptor instead.
func (*WeatherData) Descriptor() ([]byte, []int) {
	return file_weather_proto_rawDescGZIP(), []int{6}
}

func (x *WeatherData) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *WeatherData) GetLocationName() string {
	if x != nil {
		return x.LocationName
	}
	return ""
}

func (x *WeatherData) GetWeatherMain() string {
	if x != nil {
		return x.WeatherMain
	}
	return ""
}

func (x *WeatherData) GetWeatherDescription() string {
	if x != nil {
		return x.WeatherDescription
	}
	return ""
}

func (x *WeatherData) GetWeatherIcon() string {
	if x != nil {
		return x.WeatherIcon
	}
	return ""
}

func (x *WeatherData) GetTemperatureCelsius() int32 {
	if x != nil {
		return x.TemperatureCelsius
	}
	return 0
}

func (x *WeatherData) GetFeelsLikeCelsius() int32 {
	if x != nil {
		return x.FeelsLikeCelsius
	}
	return 0
}

func (x *WeatherData) GetHumidityPercent() int32 {
	if x != nil {
		return x.HumidityPercent
	}
	return 0
}

func (x *WeatherData) GetWindSpeedKmh() int32 {
	if x != nil {
		return x.WindSpeedKmh
	}
	return 0
}

func (x *WeatherData) GetWindDirectionDegrees() int32 {
	if x != nil {
		return x.WindDirectionDegrees
	}
	return 0
}

func (x *WeatherData) GetVisibilityKm() int32 {
	if x != nil {
		return x.VisibilityKm
	}
	return 0
}

func (x *WeatherData) GetAlerts() []*WeatherAlert {
	if x != nil {
		return x.Alerts
	}
	return nil
}

// FireWeather classifies fire-weather risk derived from authoritative NWS
// fire-weather products. It escalates Normal -> Elevated -> Red Flag. Red Flag
// is only reported when an NWS Red Flag Warning is actually in effect.
type FireWeather struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         FireWeatherState       `protobuf:"varint,1,opt,name=state,proto3,enum=api.v1.FireWeatherState" json:"state,omitempty"`  // normal | elevated | red-flag
	SourceEvent   string                 `protobuf:"bytes,2,opt,name=source_event,json=sourceEvent,proto3" json:"source_event,omitempty"` // Driving NWS product (e.g. "Red Flag Warning"); empty when normal
	Headline      string                 `protobuf:"bytes,3,opt,name=headline,proto3" json:"headline,omitempty"`                          // Headline of the governing alert
	SenderName    string                 `protobuf:"bytes,4,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`    // Issuing NWS office
	Effective     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=effective,proto3" json:"effective,omitempty"`                        // Start of the governing product
	Expires       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires,proto3" json:"expires,omitempty"`                            // End of the governing product
	Zones         []string               `protobuf:"bytes,7,rep,name=zones,proto3" json:"zones,omitempty"`                                // NWS zones the classification is based on
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FireWeather) Reset() {
	*x = FireWeather{}
	mi := &file_weather_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FireWeather) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FireWeather) ProtoMessage() {}

func (x *FireWeather) ProtoReflect() protoreflect.Message {
	mi := &file_weather_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FireWeather.ProtoReflect.Descriptor instead.
func (*FireWeather) Descriptor() ([]byte, []int) {
	return file_weather_proto_rawDescGZIP(), []int{7}
}

func (x *FireWeather) GetState() FireWeatherState {
	if x != nil {
		return x.State
	}
	return FireWeatherState_FIRE_WEATHER_STATE_UNSPECIFIED
}

func (x *FireWeather) GetSourceEvent() string {
	if x != nil {
		return x.SourceEvent
	}
	return ""
}

func (x *FireWeather) GetHeadline() string {
	if x != nil {
		return x.Headline
	}
	return ""
}

func (x *FireWeather) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *FireWeather) GetEffective() *timestamppb.Timestamp {
	if x != nil {
		return x.Effective
	}
	return nil
}

func (x *FireWeather) GetExpires() *timestamppb.Timestamp {
	if x != nil {
		return x.Expires
	}
	return nil
}

func (x *FireWeather) GetZones() []string {
	if x != nil {
		return x.Zones
	}
	return nil
}

type WeatherAlert struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                   // Generated unique identifier
	SenderName  string                 `protobuf:"bytes,2,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"` // Alert issuing organization
	Event       string                 `protobuf:"bytes,3,opt,name=event,proto3" json:"event,omitempty"`                             // Alert event type ("Heat Advisory", "Winter Storm Warning")
	Description string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`                 // Original NWS alert description (preserved for reference)
	Tags        []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`                               // OpenWeatherMap alert tags
	// AI-enhanced fields for improved readability
	Headline string `protobuf:"bytes,8,opt,name=headline,proto3" json:"headline,omitempty"` // Single sentence summary, <100 chars
	Summary  string `protobuf:"bytes,9,opt,name=summary,proto3" json:"summary,omitempty"`   // 2-3 sentences, plain text, traveler-focused
	Details  string `protobuf:"bytes,10,opt,name=details,proto3" json:"details,omitempty"`  // Full description with minimal markdown formatting
	// Provenance / NWS fields
	Source        AlertSource            `protobuf:"varint,11,opt,name=source,proto3,enum=api.v1.AlertSource" json:"source,omitempty"`       // Which upstream feed produced the alert
	Severity      AlertSeverity          `protobuf:"varint,12,opt,name=severity,proto3,enum=api.v1.AlertSeverity" json:"severity,omitempty"` // Severity (NWS levels mapped onto the shared scale)
	Zones         []string               `protobuf:"bytes,13,rep,name=zones,proto3" json:"zones,omitempty"`                                  // NWS forecast zones this alert applies to (e.g. "CAZ064")
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`         // When the alert becomes effective
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`               // When the alert expires
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeatherAlert) Reset() {
	*x = WeatherAlert{}
	mi := &file_weather_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeatherAlert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeatherAlert) ProtoMessage() {}

func (x *WeatherAlert) ProtoReflect() protoreflect.Message {
	mi := &file_weather_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeatherAlert.ProtoReflect.Descriptor instead.
func (*WeatherAlert) Descriptor() ([]byte, []int) {
	return file_weather_proto_rawDescGZIP(), []int{8}
}

func (x *WeatherAlert) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WeatherAlert) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *WeatherAlert) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *WeatherAlert) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *WeatherAlert) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *WeatherAlert) GetHeadline() string {
	if x != nil {
		return x.Headline
	}
	return ""
}

func (x *WeatherAlert) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *WeatherAlert) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *WeatherAlert) GetSource() AlertSource {
	if x != nil {
		return x.Source
	}
	return AlertSource_ALERT_SOURCE_UNSPECIFIED
}

func (x *WeatherAlert) GetSeverity() AlertSeverity {
	if x != nil {
		return x.Severity
	}
	return AlertSeverity_ALERT_SEVERITY_UNSPECIFIED
}

func (x *WeatherAlert) GetZones() []string {
	if x != nil {
		return x.Zones
	}
	return nil
}

func (x *WeatherAlert) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *WeatherAlert) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

var File_weather_proto protoreflect.FileDescriptor

const file_weather_proto_rawDesc = "" +
	"\n" +
	"\rweather.proto\x12\x06api.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\fcommon.proto\"\x14\n" +
	"\x12ListWeatherRequest\"<\n" +
	"\x19GetLocationWeatherRequest\x12\x1f\n" +
	"\vlocation_id\x18\x01 \x01(\tR\n" +
	"locationId\"0\n" +
	"\x18ListWeatherAlertsRequest\x12\x14\n" +
	"\x05zones\x18\x01 \x03(\tR\x05zones\"\xc4\x01\n" +
	"\x13ListWeatherResponse\x126\n" +
	"\fweather_data\x18\x01 \x03(\v2\x13.api.v1.WeatherDataR\vweatherData\x12=\n" +
	"\flast_updated\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\x126\n" +
	"\ffire_weather\x18\x03 \x01(\v2\x13.api.v1.FireWeatherR\vfireWeather\"\xcb\x01\n" +
	"\x1aGetLocationWeatherResponse\x126\n" +
	"\fweather_data\x18\x01 \x01(\v2\x13.api.v1.WeatherDataR\vweatherData\x12=\n" +
	"\flast_updated\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\x126\n" +
	"\ffire_weather\x18\x03 \x01(\v2\x13.api.v1.FireWeatherR\vfireWeather\"\x88\x01\n" +
	"\x19ListWeatherAlertsResponse\x12,\n" +
	"\x06alerts\x18\x01 \x03(\v2\x14.api.v1.WeatherAlertR\x06alerts\x12=\n" +
	"\flast_updated\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\"\x97\x04\n" +
	"\vWeatherData\x12\x1f\n" +
	"\vlocation_id\x18\x01 \x01(\tR\n" +
	"locationId\x12#\n" +
	"\rlocation_name\x18\x02 \x01(\tR\flocationName\x12!\n" +
	"\fweather_main\x18\x03 \x01(\tR\vweatherMain\x12/\n" +
	"\x13weather_description\x18\x04 \x01(\tR\x12weatherDescription\x12!\n" +
	"\fweather_icon\x18\x05 \x01(\tR\vweatherIcon\x12/\n" +
	"\x13temperature_celsius\x18\x06 \x01(\x05R\x12temperatureCelsius\x12,\n" +
	"\x12feels_like_celsius\x18\a \x01(\x05R\x10feelsLikeCelsius\x12)\n" +
	"\x10humidity_percent\x18\b \x01(\x05R\x0fhumidityPercent\x12$\n" +
	"\x0ewind_speed_kmh\x18\t \x01(\x05R\fwindSpeedKmh\x124\n" +
	"\x16wind_direction_degrees\x18\n" +
	" \x01(\x05R\x14windDirectionDegrees\x12#\n" +
	"\rvisibility_km\x18\v \x01(\x05R\fvisibilityKm\x12,\n" +
	"\x06alerts\x18\f \x03(\v2\x14.api.v1.WeatherAlertR\x06alertsJ\x04\b\r\x10\x0eR\ffire_weather\"\xa3\x02\n" +
	"\vFireWeather\x12.\n" +
	"\x05state\x18\x01 \x01(\x0e2\x18.api.v1.FireWeatherStateR\x05state\x12!\n" +
	"\fsource_event\x18\x02 \x01(\tR\vsourceEvent\x12\x1a\n" +
	"\bheadline\x18\x03 \x01(\tR\bheadline\x12\x1f\n" +
	"\vsender_name\x18\x04 \x01(\tR\n" +
	"senderName\x128\n" +
	"\teffective\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\teffective\x124\n" +
	"\aexpires\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aexpires\x12\x14\n" +
	"\x05zones\x18\a \x03(\tR\x05zones\"\xef\x03\n" +
	"\fWeatherAlert\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vsender_name\x18\x02 \x01(\tR\n" +
	"senderName\x12\x14\n" +
	"\x05event\x18\x03 \x01(\tR\x05event\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\x12\x1a\n" +
	"\bheadline\x18\b \x01(\tR\bheadline\x12\x18\n" +
	"\asummary\x18\t \x01(\tR\asummary\x12\x18\n" +
	"\adetails\x18\n" +
	" \x01(\tR\adetails\x12+\n" +
	"\x06source\x18\v \x01(\x0e2\x13.api.v1.AlertSourceR\x06source\x121\n" +
	"\bseverity\x18\f \x01(\x0e2\x15.api.v1.AlertSeverityR\bseverity\x12\x14\n" +
	"\x05zones\x18\r \x03(\tR\x05zones\x129\n" +
	"\n" +
	"start_time\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\aendTimeJ\x04\b\x04\x10\x05J\x04\b\x05\x10\x06R\x0fstart_timestampR\rend_timestamp2\xf0\x02\n" +
	"\x0eWeatherService\x12_\n" +
	"\vListWeather\x12\x1a.api.v1.ListWeatherRequest\x1a\x1b.api.v1.ListWeatherResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/api/v1/weather\x12\x82\x01\n" +
	"\x12GetLocationWeather\x12!.api.v1.GetLocationWeatherRequest\x1a\".api.v1.GetLocationWeatherResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/api/v1/weather/{location_id}\x12x\n" +
	"\x11ListWeatherAlerts\x12 .api.v1.ListWeatherAlertsRequest\x1a!.api.v1.ListWeatherAlertsResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/v1/weather/alertsB\xae\x02\x92A\x86\x02\x12\x9f\x01\n" +
	"\x18The Grid — Weather API\x12CReal-time weather conditions and alerts for the Ebbetts Pass region\"9\n" +
	"\x16The Grid (S.I.E.R.R.A)\x12\x1fhttps://data.sierragridteam.org2\x031.0*\x02\x02\x012\x10application/json:\x10application/jsonr:\n" +
	"\x13More about The Grid\x12#https://github.com/dpup/sierra-dataZ\"github.com/dpup/sierra-data/api/v1b\x06proto3"

var (
	file_weather_proto_rawDescOnce sync.Once
	file_weather_proto_rawDescData []byte
)

func file_weather_proto_rawDescGZIP() []byte {
	file_weather_proto_rawDescOnce.Do(func() {
		file_weather_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_weather_proto_rawDesc), len(file_weather_proto_rawDesc)))
	})
	return file_weather_proto_rawDescData
}

var file_weather_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_weather_proto_goTypes = []any{
	(*ListWeatherRequest)(nil),         // 0: api.v1.ListWeatherRequest
	(*GetLocationWeatherRequest)(nil),  // 1: api.v1.GetLocationWeatherRequest
	(*ListWeatherAlertsRequest)(nil),   // 2: api.v1.ListWeatherAlertsRequest
	(*ListWeatherResponse)(nil),        // 3: api.v1.ListWeatherResponse
	(*GetLocationWeatherResponse)(nil), // 4: api.v1.GetLocationWeatherResponse
	(*ListWeatherAlertsResponse)(nil),  // 5: api.v1.ListWeatherAlertsResponse
	(*WeatherData)(nil),                // 6: api.v1.WeatherData
	(*FireWeather)(nil),                // 7: api.v1.FireWeather
	(*WeatherAlert)(nil),               // 8: api.v1.WeatherAlert
	(*timestamppb.Timestamp)(nil),      // 9: google.protobuf.Timestamp
	(FireWeatherState)(0),              // 10: api.v1.FireWeatherState
	(AlertSource)(0),                   // 11: api.v1.AlertSource
	(AlertSeverity)(0),                 // 12: api.v1.AlertSeverity
}
var file_weather_proto_depIdxs = []int32{
	6,  // 0: api.v1.ListWeatherResponse.weather_data:type_name -> api.v1.WeatherData
	9,  // 1: api.v1.ListWeatherResponse.last_updated:type_name -> google.protobuf.Timestamp
	7,  // 2: api.v1.ListWeatherResponse.fire_weather:type_name -> api.v1.FireWeather
	6,  // 3: api.v1.GetLocationWeatherResponse.weather_data:type_name -> api.v1.WeatherData
	9,  // 4: api.v1.GetLocationWeatherResponse.last_updated:type_name -> google.protobuf.Timestamp
	7,  // 5: api.v1.GetLocationWeatherResponse.fire_weather:type_name -> api.v1.FireWeather
	8,  // 6: api.v1.ListWeatherAlertsResponse.alerts:type_name -> api.v1.WeatherAlert
	9,  // 7: api.v1.ListWeatherAlertsResponse.last_updated:type_name -> google.protobuf.Timestamp
	8,  // 8: api.v1.WeatherData.alerts:type_name -> api.v1.WeatherAlert
	10, // 9: api.v1.FireWeather.state:type_name -> api.v1.FireWeatherState
	9,  // 10: api.v1.FireWeather.effective:type_name -> google.protobuf.Timestamp
	9,  // 11: api.v1.FireWeather.expires:type_name -> google.protobuf.Timestamp
	11, // 12: api.v1.WeatherAlert.source:type_name -> api.v1.AlertSource
	12, // 13: api.v1.WeatherAlert.severity:type_name -> api.v1.AlertSeverity
	9,  // 14: api.v1.WeatherAlert.start_time:type_name -> google.protobuf.Timestamp
	9,  // 15: api.v1.WeatherAlert.end_time:type_name -> google.protobuf.Timestamp
	0,  // 16: api.v1.WeatherService.ListWeather:input_type -> api.v1.ListWeatherRequest
	1,  // 17: api.v1.WeatherService.GetLocationWeather:input_type -> api.v1.GetLocationWeatherRequest
	2,  // 18: api.v1.WeatherService.ListWeatherAlerts:input_type -> api.v1.ListWeatherAlertsRequest
	3,  // 19: api.v1.WeatherService.ListWeather:output_type -> api.v1.ListWeatherResponse
	4,  // 20: api.v1.WeatherService.GetLocationWeather:output_type -> api.v1.GetLocationWeatherResponse
	5,  // 21: api.v1.WeatherService.ListWeatherAlerts:output_type -> api.v1.ListWeatherAlertsResponse
	19, // [19:22] is the sub-list for method output_type
	16, // [16:19] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_weather_proto_init() }
func file_weather_proto_init() {
	if File_weather_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_weather_proto_rawDesc), len(file_weather_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_weather_proto_goTypes,
		DependencyIndexes: file_weather_proto_depIdxs,
		MessageInfos:      file_weather_proto_msgTypes,
	}.Build()
	File_weather_proto = out.File
	file_weather_proto_goTypes = nil
	file_weather_proto_depIdxs = nil
}
