// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: weather.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WeatherService_ListWeather_FullMethodName        = "/api.v1.WeatherService/ListWeather"
	WeatherService_GetLocationWeather_FullMethodName = "/api.v1.WeatherService/GetLocationWeather"
	WeatherService_ListWeatherAlerts_FullMethodName  = "/api.v1.WeatherService/ListWeatherAlerts"
)

// WeatherServiceClient is the client API for WeatherService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WeatherService provides current weather conditions and alerts
type WeatherServiceClient interface {
	// ListWeather returns current weather for all configured locations
	ListWeather(ctx context.Context, in *ListWeatherRequest, opts ...grpc.CallOption) (*ListWeatherResponse, error)
	// GetLocationWeather returns weather for a specific location
	GetLocationWeather(ctx context.Context, in *GetLocationWeatherRequest, opts ...grpc.CallOption) (*GetLocationWeatherResponse, error)
	// ListWeatherAlerts returns active weather alerts for all locations
	ListWeatherAlerts(ctx context.Context, in *ListWeatherAlertsRequest, opts ...grpc.CallOption) (*ListWeatherAlertsResponse, error)
}

type weatherServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWeatherServiceClient(cc grpc.ClientConnInterface) WeatherServiceClient {
	return &weatherServiceClient{cc}
}

func (c *weatherServiceClient) ListWeather(ctx context.Context, in *ListWeatherRequest, opts ...grpc.CallOption) (*ListWeatherResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWeatherResponse)
	err := c.cc.Invoke(ctx, WeatherService_ListWeather_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *weatherServiceClient) GetLocationWeather(ctx context.Context, in *GetLocationWeatherRequest, opts ...grpc.CallOption) (*GetLocationWeatherResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLocationWeatherResponse)
	err := c.cc.Invoke(ctx, WeatherService_GetLocationWeather_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *weatherServiceClient) ListWeatherAlerts(ctx context.Context, in *ListWeatherAlertsRequest, opts ...grpc.CallOption) (*ListWeatherAlertsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWeatherAlertsResponse)
	err := c.cc.Invoke(ctx, WeatherService_ListWeatherAlerts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WeatherServiceServer is the server API for WeatherService service.
// All implementations must embed UnimplementedWeatherServiceServer
// for forward compatibility.
//
// WeatherService provides current weather conditions and alerts
type WeatherServiceServer interface {
	// ListWeather returns current weather for all configured locations
	ListWeather(context.Context, *ListWeatherRequest) (*ListWeatherResponse, error)
	// GetLocationWeather returns weather for a specific location
	GetLocationWeather(context.Context, *GetLocationWeatherRequest) (*GetLocationWeatherResponse, error)
	// ListWeatherAlerts returns active weather alerts for all locations
	ListWeatherAlerts(context.Context, *ListWeatherAlertsRequest) (*ListWeatherAlertsResponse, error)
	mustEmbedUnimplementedWeatherServiceServer()
}

// UnimplementedWeatherServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWeatherServiceServer struct{}

func (UnimplementedWeatherServiceServer) ListWeather(context.Context, *ListWeatherRequest) (*ListWeatherResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWeather not implemented")
}
func (UnimplementedWeatherServiceServer) GetLocationWeather(context.Context, *GetLocationWeatherRequest) (*GetLocationWeatherResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLocationWeather not implemented")
}
func (UnimplementedWeatherServiceServer) ListWeatherAlerts(context.Context, *ListWeatherAlertsRequest) (*ListWeatherAlertsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWeatherAlerts not implemented")
}
func (UnimplementedWeatherServiceServer) mustEmbedUnimplementedWeatherServiceServer() {}
func (UnimplementedWeatherServiceServer) testEmbeddedByValue()                        {}

// UnsafeWeatherServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WeatherServiceServer will
// result in compilation errors.
type UnsafeWeatherServiceServer interface {
	mustEmbedUnimplementedWeatherServiceServer()
}

func RegisterWeatherServiceServer(s grpc.ServiceRegistrar, srv WeatherServiceServer) {
	// If the following call pancis, it indicates UnimplementedWeatherServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WeatherService_ServiceDesc, srv)
}

func _WeatherService_ListWeather_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWeatherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeatherServiceServer).ListWeather(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WeatherService_ListWeather_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeatherServiceServer).ListWeather(ctx, req.(*ListWeatherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WeatherService_GetLocationWeather_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLocationWeatherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeatherServiceServer).GetLocationWeather(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WeatherService_GetLocationWeather_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeatherServiceServer).GetLocationWeather(ctx, req.(*GetLocationWeatherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WeatherService_ListWeatherAlerts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWeatherAlertsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeatherServiceServer).ListWeatherAlerts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WeatherService_ListWeatherAlerts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeatherServiceServer).ListWeatherAlerts(ctx, req.(*ListWeatherAlertsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WeatherService_ServiceDesc is the grpc.ServiceDesc for WeatherService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WeatherService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.WeatherService",
	HandlerType: (*WeatherServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListWeather",
			Handler:    _WeatherService_ListWeather_Handler,
		},
		{
			MethodName: "GetLocationWeather",
			Handler:    _WeatherService_GetLocationWeather_Handler,
		},
		{
			MethodName: "ListWeatherAlerts",
			Handler:    _WeatherService_ListWeatherAlerts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "weather.proto",
}
