// Package placesdata embeds the checked-in place-directory seed geometry.
// The embed directive cannot reference files outside the package directory, so
// this package lives beside the data it exposes; internal/places consumes it.
package placesdata

import _ "embed"

// CountiesGeoJSON is the Census TIGERweb generalized (1:500k) county polygon
// FeatureCollection. Provenance and post-processing: README.md alongside.
//
//go:embed counties.geojson
var CountiesGeoJSON []byte

// AreasGeoJSON holds hand-drawn coverage polygons for hazard areas, keyed by the
// area id in each feature's properties. Optional per area: an area with no
// feature here falls back to its configured bbox rectangle. See README.md.
//
//go:embed areas.geojson
var AreasGeoJSON []byte

// CorridorsGeoJSON holds the real road path (decoded Google Routes polyline) for
// each monitored road, keyed by the road id in each feature's properties.
// Generated by cmd/gen-corridors; a corridor with no feature here falls back to
// the straight origin->destination chord. See README.md.
//
//go:embed corridors.geojson
var CorridorsGeoJSON []byte
