// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: grid.proto

package gridv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Layer int32

const (
	Layer_LAYER_UNSPECIFIED Layer = 0
	Layer_WILDFIRE          Layer = 1
	Layer_EVACUATION        Layer = 2
	Layer_WEATHER_ALERT     Layer = 3
	Layer_FIRE_WEATHER      Layer = 4
	Layer_EARTHQUAKE        Layer = 5
	Layer_ROAD_INCIDENT     Layer = 6
	// condition-backed layers (ROAD_SEGMENT, CHAIN_CONTROL) are projections, not events
	Layer_POWER        Layer = 10
	Layer_GAUGE        Layer = 11
	Layer_AIR_QUALITY  Layer = 12
	Layer_NETWORK      Layer = 13
	Layer_ANNOUNCEMENT Layer = 14
)

// Enum value maps for Layer.
var (
	Layer_name = map[int32]string{
		0:  "LAYER_UNSPECIFIED",
		1:  "WILDFIRE",
		2:  "EVACUATION",
		3:  "WEATHER_ALERT",
		4:  "FIRE_WEATHER",
		5:  "EARTHQUAKE",
		6:  "ROAD_INCIDENT",
		10: "POWER",
		11: "GAUGE",
		12: "AIR_QUALITY",
		13: "NETWORK",
		14: "ANNOUNCEMENT",
	}
	Layer_value = map[string]int32{
		"LAYER_UNSPECIFIED": 0,
		"WILDFIRE":          1,
		"EVACUATION":        2,
		"WEATHER_ALERT":     3,
		"FIRE_WEATHER":      4,
		"EARTHQUAKE":        5,
		"ROAD_INCIDENT":     6,
		"POWER":             10,
		"GAUGE":             11,
		"AIR_QUALITY":       12,
		"NETWORK":           13,
		"ANNOUNCEMENT":      14,
	}
)

func (x Layer) Enum() *Layer {
	p := new(Layer)
	*p = x
	return p
}

func (x Layer) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Layer) Descriptor() protoreflect.EnumDescriptor {
	return file_grid_proto_enumTypes[0].Descriptor()
}

func (Layer) Type() protoreflect.EnumType {
	return &file_grid_proto_enumTypes[0]
}

func (x Layer) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Layer.Descriptor instead.
func (Layer) EnumDescriptor() ([]byte, []int) {
	return file_grid_proto_rawDescGZIP(), []int{0}
}

// The shipped scale, unchanged. rank = enum value; INFO=0 ... EXTREME=4.
type Severity int32

const (
	Severity_INFO     Severity = 0
	Severity_MINOR    Severity = 1
	Severity_MODERATE Severity = 2
	Severity_SEVERE   Severity = 3
	Severity_EXTREME  Severity = 4
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "INFO",
		1: "MINOR",
		2: "MODERATE",
		3: "SEVERE",
		4: "EXTREME",
	}
	Severity_value = map[string]int32{
		"INFO":     0,
		"MINOR":    1,
		"MODERATE": 2,
		"SEVERE":   3,
		"EXTREME":  4,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_grid_proto_enumTypes[1].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_grid_proto_enumTypes[1]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_grid_proto_rawDescGZIP(), []int{1}
}

type EventStatus int32

const (
	EventStatus_EVENT_STATUS_UNSPECIFIED EventStatus = 0
	EventStatus_SCHEDULED                EventStatus = 1 // planned PSPS, forecast closures
	EventStatus_ACTIVE                   EventStatus = 2
	EventStatus_RESOLVED                 EventStatus = 3 // upstream confirmed over
	EventStatus_EXPIRED                  EventStatus = 4 // aged out per-source policy; upstream went quiet
)

// Enum value maps for EventStatus.
var (
	EventStatus_name = map[int32]string{
		0: "EVENT_STATUS_UNSPECIFIED",
		1: "SCHEDULED",
		2: "ACTIVE",
		3: "RESOLVED",
		4: "EXPIRED",
	}
	EventStatus_value = map[string]int32{
		"EVENT_STATUS_UNSPECIFIED": 0,
		"SCHEDULED":                1,
		"ACTIVE":                   2,
		"RESOLVED":                 3,
		"EXPIRED":                  4,
	}
)

func (x EventStatus) Enum() *EventStatus {
	p := new(EventStatus)
	*p = x
	return p
}

func (x EventStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_grid_proto_enumTypes[2].Descriptor()
}

func (EventStatus) Type() protoreflect.EnumType {
	return &file_grid_proto_enumTypes[2]
}

func (x EventStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventStatus.Descriptor instead.
func (EventStatus) EnumDescriptor() ([]byte, []int) {
	return file_grid_proto_rawDescGZIP(), []int{2}
}

type SourceStatus int32

const (
	SourceStatus_SOURCE_STATUS_UNSPECIFIED SourceStatus = 0
	SourceStatus_OK                        SourceStatus = 1
	SourceStatus_STALE                     SourceStatus = 2
	SourceStatus_UNAVAILABLE               SourceStatus = 3
)

// Enum value maps for SourceStatus.
var (
	SourceStatus_name = map[int32]string{
		0: "SOURCE_STATUS_UNSPECIFIED",
		1: "OK",
		2: "STALE",
		3: "UNAVAILABLE",
	}
	SourceStatus_value = map[string]int32{
		"SOURCE_STATUS_UNSPECIFIED": 0,
		"OK":                        1,
		"STALE":                     2,
		"UNAVAILABLE":               3,
	}
)

func (x SourceStatus) Enum() *SourceStatus {
	p := new(SourceStatus)
	*p = x
	return p
}

func (x SourceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SourceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_grid_proto_enumTypes[3].Descriptor()
}

func (SourceStatus) Type() protoreflect.EnumType {
	return &file_grid_proto_enumTypes[3]
}

func (x SourceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SourceStatus.Descriptor instead.
func (SourceStatus) EnumDescriptor() ([]byte, []int) {
	return file_grid_proto_rawDescGZIP(), []int{3}
}

type PlaceKind int32

const (
	PlaceKind_PLACE_KIND_UNSPECIFIED PlaceKind = 0
	PlaceKind_AREA                   PlaceKind = 1 // existing configured areas; org footprints live here too
	PlaceKind_COUNTY                 PlaceKind = 2
	PlaceKind_TOWN                   PlaceKind = 3
	PlaceKind_EVAC_ZONE              PlaceKind = 4
	PlaceKind_CORRIDOR               PlaceKind = 5
	PlaceKind_SITE                   PlaceKind = 6
)

// Enum value maps for PlaceKind.
var (
	PlaceKind_name = map[int32]string{
		0: "PLACE_KIND_UNSPECIFIED",
		1: "AREA",
		2: "COUNTY",
		3: "TOWN",
		4: "EVAC_ZONE",
		5: "CORRIDOR",
		6: "SITE",
	}
	PlaceKind_value = map[string]int32{
		"PLACE_KIND_UNSPECIFIED": 0,
		"AREA":                   1,
		"COUNTY":                 2,
		"TOWN":                   3,
		"EVAC_ZONE":              4,
		"CORRIDOR":               5,
		"SITE":                   6,
	}
)

func (x PlaceKind) Enum() *PlaceKind {
	p := new(PlaceKind)
	*p = x
	return p
}

func (x PlaceKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlaceKind) Descriptor() protoreflect.EnumDescriptor {
	return file_grid_proto_enumTypes[4].Descriptor()
}

func (PlaceKind) Type() protoreflect.EnumType {
	return &file_grid_proto_enumTypes[4]
}

func (x PlaceKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlaceKind.Descriptor instead.
func (PlaceKind) EnumDescriptor() ([]byte, []int) {
	return file_grid_proto_rawDescGZIP(), []int{4}
}

type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // "{source_id}:{native_id}" — matches shipped ids
	// e.g. "calfire:2026-salt-springs"
	Layer        Layer                  `protobuf:"varint,2,opt,name=layer,proto3,enum=grid.v1.Layer" json:"layer,omitempty"`          // shipped taxonomy + additions
	Category     string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`                        // source sub-type slug ("active", "order", ...)
	Severity     Severity               `protobuf:"varint,4,opt,name=severity,proto3,enum=grid.v1.Severity" json:"severity,omitempty"` // shipped 5-level scale
	Status       EventStatus            `protobuf:"varint,5,opt,name=status,proto3,enum=grid.v1.EventStatus" json:"status,omitempty"`
	Headline     string                 `protobuf:"bytes,6,opt,name=headline,proto3" json:"headline,omitempty"`                              // card-renderable without knowing the kind
	Summary      string                 `protobuf:"bytes,7,opt,name=summary,proto3" json:"summary,omitempty"`                                // AI-enhanced 2–3 sentences where applicable
	Description  string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`                        // long form / original text
	AreaLabel    string                 `protobuf:"bytes,9,opt,name=area_label,json=areaLabel,proto3" json:"area_label,omitempty"`           // "Hathaway Pines & Avery"
	CanonicalUrl string                 `protobuf:"bytes,10,opt,name=canonical_url,json=canonicalUrl,proto3" json:"canonical_url,omitempty"` // scheme-validated (https/http only, per shipped rule)
	Geometry     *Geometry              `protobuf:"bytes,11,opt,name=geometry,proto3" json:"geometry,omitempty"`                             // may be absent: county-wide advisories
	PlaceIds     []string               `protobuf:"bytes,12,rep,name=place_ids,json=placeIds,proto3" json:"place_ids,omitempty"`             // precomputed intersections (spec §4)
	Provenance   *Provenance            `protobuf:"bytes,13,opt,name=provenance,proto3" json:"provenance,omitempty"`
	Effective    *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=effective,proto3" json:"effective,omitempty"`
	Expires      *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=expires,proto3" json:"expires,omitempty"`
	ObservedAt   *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"` // upstream last-update
	IngestedAt   *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=ingested_at,json=ingestedAt,proto3" json:"ingested_at,omitempty"`
	Revision     uint32                 `protobuf:"varint,18,opt,name=revision,proto3" json:"revision,omitempty"`
	Enhancement  *Enhancement           `protobuf:"bytes,19,opt,name=enhancement,proto3" json:"enhancement,omitempty"` // AI-enhancement provenance (spec §3.1)
	// Types that are valid to be assigned to Detail:
	//
	//	*Event_Wildfire
	//	*Event_Evacuation
	//	*Event_WeatherAlert
	//	*Event_FireWeather
	//	*Event_Earthquake
	//	*Event_RoadIncident
	Detail        isEvent_Detail `protobuf_oneof:"detail"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_grid_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_grid_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_grid_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetLayer() Layer {
	if x != nil {
		return x.Layer
	}
	return Layer_LAYER_UNSPECIFIED
}

func (x *Event) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Event) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_INFO
}

func (x *Event) GetStatus() EventStatus {
	if x != nil {
		return x.Status
	}
	return EventStatus_EVENT_STATUS_UNSPECIFIED
}

func (x *Event) GetHeadline() string {
	if x != nil {
		return x.Headline
	}
	return ""
}

func (x *Event) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Event) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Event) GetAreaLabel() string {
	if x != nil {
		return x.AreaLabel
	}
	return ""
}

func (x *Event) GetCanonicalUrl() string {
	if x != nil {
		return x.CanonicalUrl
	}
	return ""
}

func (x *Event) GetGeometry() *Geometry {
	if x != nil {
		return x.Geometry
	}
	return nil
}

func (x *Event) GetPlaceIds() []string {
	if x != nil {
		return x.PlaceIds
	}
	return nil
}

func (x *Event) GetProvenance() *Provenance {
	if x != nil {
		return x.Provenance
	}
	return nil
}

func (x *Event) GetEffective() *timestamppb.Timestamp {
	if x != nil {
		return x.Effective
	}
	return nil
}

func (x *Event) GetExpires() *timestamppb.Timestamp {
	if x != nil {
		return x.Expires
	}
	return nil
}

func (x *Event) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *Event) GetIngestedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IngestedAt
	}
	return nil
}

func (x *Event) GetRevision() uint32 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *Event) GetEnhancement() *Enhancement {
	if x != nil {
		return x.Enhancement
	}
	return nil
}

func (x *Event) GetDetail() isEvent_Detail {
	if x != nil {
		return x.Detail
	}
	return nil
}

func (x *Event) GetWildfire() *WildfireDetail {
	if x != nil {
		if x, ok := x.Detail.(*Event_Wildfire); ok {
			return x.Wildfire
		}
	}
	return nil
}

func (x *Event) GetEvacuation() *EvacuationDetail {
	if x != nil {
		if x, ok := x.Detail.(*Event_Evacuation); ok {
			return x.Evacuation
		}
	}
	return nil
}

func (x *Event) GetWeatherAlert() *WeatherAlertDetail {
	if x != nil {
		if x, ok := x.Detail.(*Event_WeatherAlert); ok {
			return x.WeatherAlert
		}
	}
	return nil
}

func (x *Event) GetFireWeather() *FireWeatherDetail {
	if x != nil {
		if x, ok := x.Detail.(*Event_FireWeather); ok {
			return x.FireWeather
		}
	}
	return nil
}

func (x *Event) GetEarthquake() *EarthquakeDetail {
	if x != nil {
		if x, ok := x.Detail.(*Event_Earthquake); ok {
			return x.Earthquake
		}
	}
	return nil
}

func (x *Event) GetRoadIncident() *RoadIncidentDetail {
	if x != nil {
		if x, ok := x.Detail.(*Event_RoadIncident); ok {
			return x.RoadIncident
		}
	}
	return nil
}

type isEvent_Detail interface {
	isEvent_Detail()
}

type Event_Wildfire struct {
	Wildfire *WildfireDetail `protobuf:"bytes,20,opt,name=wildfire,proto3,oneof"`
}

type Event_Evacuation struct {
	Evacuation *EvacuationDetail `protobuf:"bytes,21,opt,name=evacuation,proto3,oneof"`
}

type Event_WeatherAlert struct {
	WeatherAlert *WeatherAlertDetail `protobuf:"bytes,22,opt,name=weather_alert,json=weatherAlert,proto3,oneof"`
}

type Event_FireWeather struct {
	FireWeather *FireWeatherDetail `protobuf:"bytes,23,opt,name=fire_weather,json=fireWeather,proto3,oneof"`
}

type Event_Earthquake struct {
	Earthquake *EarthquakeDetail `protobuf:"bytes,24,opt,name=earthquake,proto3,oneof"`
}

type Event_RoadIncident struct {
	RoadIncident *RoadIncidentDetail `protobuf:"bytes,25,opt,name=road_incident,json=roadIncident,proto3,oneof"`
}

func (*Event_Wildfire) isEvent_Detail() {}

func (*Event_Evacuation) isEvent_Detail() {}

func (*Event_WeatherAlert) isEvent_Detail() {}

func (*Event_FireWeather) isEvent_Detail() {}

func (*Event_Earthquake) isEvent_Detail() {}

func (*Event_RoadIncident) isEvent_Detail() {}

type Geometry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Geojson       []byte                 `protobuf:"bytes,1,opt,name=geojson,proto3" json:"geojson,omitempty"` // RFC 7946 geometry object, UTF-8
	Bbox          *BoundingBox           `protobuf:"bytes,2,opt,name=bbox,proto3" json:"bbox,omitempty"`       // always populated at ingest
	Centroid      *LatLng                `protobuf:"bytes,3,opt,name=centroid,proto3" json:"centroid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Geometry) Reset() {
	*x = Geometry{}
	mi := &file_grid_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Geometry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Geometry) ProtoMessage() {}

func (x *Geometry) ProtoReflect() protoreflect.Message {
	mi := &file_grid_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Geometry.ProtoReflect.Descriptor instead.
func (*Geometry) Descriptor() ([]byte, []int) {
	return file_grid_proto_rawDescGZIP(), []int{1}
}

func (x *Geometry) GetGeojson() []byte {
	if x != nil {
		return x.Geojson
	}
	return nil
}

func (x *Geometry) GetBbox() *BoundingBox {
	if x != nil {
		return x.Bbox
	}
	return nil
}

func (x *Geometry) GetCentroid() *LatLng {
	if x != nil {
		return x.Centroid
	}
	return nil
}

type BoundingBox struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinLat        float64                `protobuf:"fixed64,1,opt,name=min_lat,json=minLat,proto3" json:"min_lat,omitempty"`
	MinLng        float64                `protobuf:"fixed64,2,opt,name=min_lng,json=minLng,proto3" json:"min_lng,omitempty"`
	MaxLat        float64                `protobuf:"fixed64,3,opt,name=max_lat,json=maxLat,proto3" json:"max_lat,omitempty"`
	MaxLng        float64                `protobuf:"fixed64,4,opt,name=max_lng,json=maxLng,proto3" json:"max_lng,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoundingBox) Reset() {
	*x = BoundingBox{}
	mi := &file_grid_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoundingBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoundingBox) ProtoMessage() {}

func (x *BoundingBox) ProtoReflect() protoreflect.Message {
	mi := &file_grid_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoundingBox.ProtoReflect.Descriptor instead.
func (*BoundingBox) Descriptor() ([]byte, []int) {
	return file_grid_proto_rawDescGZIP(), []int{2}
}

func (x *BoundingBox) GetMinLat() float64 {
	if x != nil {
		return x.MinLat
	}
	return 0
}

func (x *BoundingBox) GetMinLng() float64 {
	if x != nil {
		return x.MinLng
	}
	return 0
}

func (x *BoundingBox) GetMaxLat() float64 {
	if x != nil {
		return x.MaxLat
	}
	return 0
}

func (x *BoundingBox) GetMaxLng() float64 {
	if x != nil {
		return x.MaxLng
	}
	return 0
}

type LatLng struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng           float64                `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatLng) Reset() {
	*x = LatLng{}
	mi := &file_grid_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatLng) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatLng) ProtoMessage() {}

func (x *LatLng) ProtoReflect() protoreflect.Message {
	mi := &file_grid_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatLng.ProtoReflect.Descriptor instead.
func (*LatLng) Descriptor() ([]byte, []int) {
	return file_grid_proto_rawDescGZIP(), []int{3}
}

func (x *LatLng) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *LatLng) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

type Provenance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	SourceName    string                 `protobuf:"bytes,2,opt,name=source_name,json=sourceName,proto3" json:"source_name,omitempty"` // denormalized: "CAL FIRE"
	Attribution   string                 `protobuf:"bytes,3,opt,name=attribution,proto3" json:"attribution,omitempty"`                 // "CAL FIRE / WFIGS"
	SourceUrl     string                 `protobuf:"bytes,4,opt,name=source_url,json=sourceUrl,proto3" json:"source_url,omitempty"`
	FetchedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=fetched_at,json=fetchedAt,proto3" json:"fetched_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Provenance) Reset() {
	*x = Provenance{}
	mi := &file_grid_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Provenance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Provenance) ProtoMessage() {}

func (x *Provenance) ProtoReflect() protoreflect.Message {
	mi := &file_grid_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Provenance.ProtoReflect.Descriptor instead.
func (*Provenance) Descriptor() ([]byte, []int) {
	return file_grid_proto_rawDescGZIP(), []int{4}
}

func (x *Provenance) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *Provenance) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *Provenance) GetAttribution() string {
	if x != nil {
		return x.Attribution
	}
	return ""
}

func (x *Provenance) GetSourceUrl() string {
	if x != nil {
		return x.SourceUrl
	}
	return ""
}

func (x *Provenance) GetFetchedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FetchedAt
	}
	return nil
}

// AI-enhancement provenance so clients can badge AI-summarized text
// (spec §3.1: translate, never assert; originals preserved in description).
type Enhancement struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Model      string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"` // "gpt-4o-mini", "claude-haiku-4-5", ...
	EnhancedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=enhanced_at,json=enhancedAt,proto3" json:"enhanced_at,omitempty"`
	Fields     []string               `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"` // which Event fields were generated
	// Transparency: the exact model input and output, so a client can show what
	// was sent and what came back. `request` is the incident-specific user prompt
	// (the static system prompt is not included); `response` is the raw structured
	// JSON the model returned. Excluded from the event content hash.
	Request       string `protobuf:"bytes,4,opt,name=request,proto3" json:"request,omitempty"`
	Response      string `protobuf:"bytes,5,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Enhancement) Reset() {
	*x = Enhancement{}
	mi := &file_grid_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Enhancement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Enhancement) ProtoMessage() {}

func (x *Enhancement) ProtoReflect() protoreflect.Message {
	mi := &file_grid_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Enhancement.ProtoReflect.Descriptor instead.
func (*Enhancement) Descriptor() ([]byte, []int) {
	return file_grid_proto_rawDescGZIP(), []int{5}
}

func (x *Enhancement) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Enhancement) GetEnhancedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EnhancedAt
	}
	return nil
}

func (x *Enhancement) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *Enhancement) GetRequest() string {
	if x != nil {
		return x.Request
	}
	return ""
}

func (x *Enhancement) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type Source struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Attribution         string                 `protobuf:"bytes,3,opt,name=attribution,proto3" json:"attribution,omitempty"`
	HomepageUrl         string                 `protobuf:"bytes,4,opt,name=homepage_url,json=homepageUrl,proto3" json:"homepage_url,omitempty"`
	PollIntervalSeconds uint32                 `protobuf:"varint,5,opt,name=poll_interval_seconds,json=pollIntervalSeconds,proto3" json:"poll_interval_seconds,omitempty"`
	StaleAfterSeconds   uint32                 `protobuf:"varint,10,opt,name=stale_after_seconds,json=staleAfterSeconds,proto3" json:"stale_after_seconds,omitempty"`    // per-source tunable; default 3x poll interval
	ExpireAfterSeconds  uint32                 `protobuf:"varint,11,opt,name=expire_after_seconds,json=expireAfterSeconds,proto3" json:"expire_after_seconds,omitempty"` // per-source tunable; missing-from-feed → EXPIRED
	LastSuccessAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_success_at,json=lastSuccessAt,proto3" json:"last_success_at,omitempty"`
	LastAttemptAt       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_attempt_at,json=lastAttemptAt,proto3" json:"last_attempt_at,omitempty"`
	LastError           string                 `protobuf:"bytes,8,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	Status              SourceStatus           `protobuf:"varint,9,opt,name=status,proto3,enum=grid.v1.SourceStatus" json:"status,omitempty"` // shipped semantics, now per-source not per-layer
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Source) Reset() {
	*x = Source{}
	mi := &file_grid_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Source) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Source) ProtoMessage() {}

func (x *Source) ProtoReflect() protoreflect.Message {
	mi := &file_grid_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Source.ProtoReflect.Descriptor instead.
func (*Source) Descriptor() ([]byte, []int) {
	return file_grid_proto_rawDescGZIP(), []int{6}
}

func (x *Source) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Source) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Source) GetAttribution() string {
	if x != nil {
		return x.Attribution
	}
	return ""
}

func (x *Source) GetHomepageUrl() string {
	if x != nil {
		return x.HomepageUrl
	}
	return ""
}

func (x *Source) GetPollIntervalSeconds() uint32 {
	if x != nil {
		return x.PollIntervalSeconds
	}
	return 0
}

func (x *Source) GetStaleAfterSeconds() uint32 {
	if x != nil {
		return x.StaleAfterSeconds
	}
	return 0
}

func (x *Source) GetExpireAfterSeconds() uint32 {
	if x != nil {
		return x.ExpireAfterSeconds
	}
	return 0
}

func (x *Source) GetLastSuccessAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSuccessAt
	}
	return nil
}

func (x *Source) GetLastAttemptAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastAttemptAt
	}
	return nil
}

func (x *Source) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *Source) GetStatus() SourceStatus {
	if x != nil {
		return x.Status
	}
	return SourceStatus_SOURCE_STATUS_UNSPECIFIED
}

type Place struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // "area:calaveras" — existing area ids preserved under a kind
	Kind          PlaceKind              `protobuf:"varint,2,opt,name=kind,proto3,enum=grid.v1.PlaceKind" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`
	Geometry      *Geometry              `protobuf:"bytes,5,opt,name=geometry,proto3" json:"geometry,omitempty"`
	ParentId      string                 `protobuf:"bytes,6,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Place) Reset() {
	*x = Place{}
	mi := &file_grid_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Place) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Place) ProtoMessage() {}

func (x *Place) ProtoReflect() protoreflect.Message {
	mi := &file_grid_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Place.ProtoReflect.Descriptor instead.
func (*Place) Descriptor() ([]byte, []int) {
	return file_grid_proto_rawDescGZIP(), []int{7}
}

func (x *Place) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Place) GetKind() PlaceKind {
	if x != nil {
		return x.Kind
	}
	return PlaceKind_PLACE_KIND_UNSPECIFIED
}

func (x *Place) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Place) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Place) GetGeometry() *Geometry {
	if x != nil {
		return x.Geometry
	}
	return nil
}

func (x *Place) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

type WildfireDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acres         float64                `protobuf:"fixed64,1,opt,name=acres,proto3" json:"acres,omitempty"`
	Containment   int32                  `protobuf:"varint,2,opt,name=containment,proto3" json:"containment,omitempty"` // percent contained, 0-100
	County        string                 `protobuf:"bytes,3,opt,name=county,proto3" json:"county,omitempty"`
	Cause         string                 `protobuf:"bytes,4,opt,name=cause,proto3" json:"cause,omitempty"`
	HasPerimeter  bool                   `protobuf:"varint,5,opt,name=has_perimeter,json=hasPerimeter,proto3" json:"has_perimeter,omitempty"` // true when geometry is a WFIGS perimeter polygon
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WildfireDetail) Reset() {
	*x = WildfireDetail{}
	mi := &file_grid_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WildfireDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WildfireDetail) ProtoMessage() {}

func (x *WildfireDetail) ProtoReflect() protoreflect.Message {
	mi := &file_grid_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WildfireDetail.ProtoReflect.Descriptor instead.
func (*WildfireDetail) Descriptor() ([]byte, []int) {
	return file_grid_proto_rawDescGZIP(), []int{8}
}

func (x *WildfireDetail) GetAcres() float64 {
	if x != nil {
		return x.Acres
	}
	return 0
}

func (x *WildfireDetail) GetContainment() int32 {
	if x != nil {
		return x.Containment
	}
	return 0
}

func (x *WildfireDetail) GetCounty() string {
	if x != nil {
		return x.County
	}
	return ""
}

func (x *WildfireDetail) GetCause() string {
	if x != nil {
		return x.Cause
	}
	return ""
}

func (x *WildfireDetail) GetHasPerimeter() bool {
	if x != nil {
		return x.HasPerimeter
	}
	return false
}

type EvacuationDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneId        string                 `protobuf:"bytes,1,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"` // ORDER | WARNING | ADVISORY | SHELTER_IN_PLACE
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	County        string                 `protobuf:"bytes,4,opt,name=county,proto3" json:"county,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvacuationDetail) Reset() {
	*x = EvacuationDetail{}
	mi := &file_grid_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvacuationDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvacuationDetail) ProtoMessage() {}

func (x *EvacuationDetail) ProtoReflect() protoreflect.Message {
	mi := &file_grid_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvacuationDetail.ProtoReflect.Descriptor instead.
func (*EvacuationDetail) Descriptor() ([]byte, []int) {
	return file_grid_proto_rawDescGZIP(), []int{9}
}

func (x *EvacuationDetail) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *EvacuationDetail) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *EvacuationDetail) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EvacuationDetail) GetCounty() string {
	if x != nil {
		return x.County
	}
	return ""
}

// Detail messages carry only KIND-SPECIFIC fields not already in the Event
// envelope. Fields that duplicate an envelope field are NOT repeated here:
//   - the NWS event name is the envelope `category`
//   - the sending office is `provenance.source_name`
type WeatherAlertDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NwsSeverity   string                 `protobuf:"bytes,1,opt,name=nws_severity,json=nwsSeverity,proto3" json:"nws_severity,omitempty"` // raw NWS vocabulary (Extreme..Minor), distinct from unified severity
	Certainty     string                 `protobuf:"bytes,2,opt,name=certainty,proto3" json:"certainty,omitempty"`
	Urgency       string                 `protobuf:"bytes,3,opt,name=urgency,proto3" json:"urgency,omitempty"`
	Instruction   string                 `protobuf:"bytes,4,opt,name=instruction,proto3" json:"instruction,omitempty"`
	AreaDesc      string                 `protobuf:"bytes,5,opt,name=area_desc,json=areaDesc,proto3" json:"area_desc,omitempty"` // NWS free-text area (no envelope equivalent for zone alerts)
	Zones         []string               `protobuf:"bytes,6,rep,name=zones,proto3" json:"zones,omitempty"`                       // NWS forecast zones, e.g. "CAZ064"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeatherAlertDetail) Reset() {
	*x = WeatherAlertDetail{}
	mi := &file_grid_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeatherAlertDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeatherAlertDetail) ProtoMessage() {}

func (x *WeatherAlertDetail) ProtoReflect() protoreflect.Message {
	mi := &file_grid_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeatherAlertDetail.ProtoReflect.Descriptor instead.
func (*WeatherAlertDetail) Descriptor() ([]byte, []int) {
	return file_grid_proto_rawDescGZIP(), []int{10}
}

func (x *WeatherAlertDetail) GetNwsSeverity() string {
	if x != nil {
		return x.NwsSeverity
	}
	return ""
}

func (x *WeatherAlertDetail) GetCertainty() string {
	if x != nil {
		return x.Certainty
	}
	return ""
}

func (x *WeatherAlertDetail) GetUrgency() string {
	if x != nil {
		return x.Urgency
	}
	return ""
}

func (x *WeatherAlertDetail) GetInstruction() string {
	if x != nil {
		return x.Instruction
	}
	return ""
}

func (x *WeatherAlertDetail) GetAreaDesc() string {
	if x != nil {
		return x.AreaDesc
	}
	return ""
}

func (x *WeatherAlertDetail) GetZones() []string {
	if x != nil {
		return x.Zones
	}
	return nil
}

// fire_weather is condition-backed (a live projection, not an event); this
// message exists for the spec §3 oneof shape.
type FireWeatherDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`                                // normal | elevated | red-flag
	SourceEvent   string                 `protobuf:"bytes,2,opt,name=source_event,json=sourceEvent,proto3" json:"source_event,omitempty"` // NWS product driving the state
	Zones         []string               `protobuf:"bytes,3,rep,name=zones,proto3" json:"zones,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FireWeatherDetail) Reset() {
	*x = FireWeatherDetail{}
	mi := &file_grid_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FireWeatherDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FireWeatherDetail) ProtoMessage() {}

func (x *FireWeatherDetail) ProtoReflect() protoreflect.Message {
	mi := &file_grid_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FireWeatherDetail.ProtoReflect.Descriptor instead.
func (*FireWeatherDetail) Descriptor() ([]byte, []int) {
	return file_grid_proto_rawDescGZIP(), []int{11}
}

func (x *FireWeatherDetail) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *FireWeatherDetail) GetSourceEvent() string {
	if x != nil {
		return x.SourceEvent
	}
	return ""
}

func (x *FireWeatherDetail) GetZones() []string {
	if x != nil {
		return x.Zones
	}
	return nil
}

type EarthquakeDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Magnitude     float64                `protobuf:"fixed64,1,opt,name=magnitude,proto3" json:"magnitude,omitempty"`
	DepthKm       float64                `protobuf:"fixed64,2,opt,name=depth_km,json=depthKm,proto3" json:"depth_km,omitempty"`
	Felt          int32                  `protobuf:"varint,3,opt,name=felt,proto3" json:"felt,omitempty"` // USGS DYFI felt-report count
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EarthquakeDetail) Reset() {
	*x = EarthquakeDetail{}
	mi := &file_grid_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EarthquakeDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EarthquakeDetail) ProtoMessage() {}

func (x *EarthquakeDetail) ProtoReflect() protoreflect.Message {
	mi := &file_grid_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EarthquakeDetail.ProtoReflect.Descriptor instead.
func (*EarthquakeDetail) Descriptor() ([]byte, []int) {
	return file_grid_proto_rawDescGZIP(), []int{12}
}

func (x *EarthquakeDetail) GetMagnitude() float64 {
	if x != nil {
		return x.Magnitude
	}
	return 0
}

func (x *EarthquakeDetail) GetDepthKm() float64 {
	if x != nil {
		return x.DepthKm
	}
	return 0
}

func (x *EarthquakeDetail) GetFelt() int32 {
	if x != nil {
		return x.Felt
	}
	return 0
}

// Kind-specific only. The incident type is the envelope `category`, the human
// location is `area_label`, and the short line is the `headline` — none are
// repeated here.
type RoadIncidentDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogNumber     string                 `protobuf:"bytes,1,opt,name=log_number,json=logNumber,proto3" json:"log_number,omitempty"`
	Impact        string                 `protobuf:"bytes,2,opt,name=impact,proto3" json:"impact,omitempty"`                                                                               // AI-assessed: none | light | moderate | severe
	Duration      string                 `protobuf:"bytes,3,opt,name=duration,proto3" json:"duration,omitempty"`                                                                           // AI-assessed: unknown | < 1 hour | several hours | ongoing
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // structured extras from AI analysis (internal keys stripped)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoadIncidentDetail) Reset() {
	*x = RoadIncidentDetail{}
	mi := &file_grid_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoadIncidentDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoadIncidentDetail) ProtoMessage() {}

func (x *RoadIncidentDetail) ProtoReflect() protoreflect.Message {
	mi := &file_grid_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoadIncidentDetail.ProtoReflect.Descriptor instead.
func (*RoadIncidentDetail) Descriptor() ([]byte, []int) {
	return file_grid_proto_rawDescGZIP(), []int{13}
}

func (x *RoadIncidentDetail) GetLogNumber() string {
	if x != nil {
		return x.LogNumber
	}
	return ""
}

func (x *RoadIncidentDetail) GetImpact() string {
	if x != nil {
		return x.Impact
	}
	return ""
}

func (x *RoadIncidentDetail) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *RoadIncidentDetail) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type EventList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventList) Reset() {
	*x = EventList{}
	mi := &file_grid_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventList) ProtoMessage() {}

func (x *EventList) ProtoReflect() protoreflect.Message {
	mi := &file_grid_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventList.ProtoReflect.Descriptor instead.
func (*EventList) Descriptor() ([]byte, []int) {
	return file_grid_proto_rawDescGZIP(), []int{14}
}

func (x *EventList) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *EventList) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type EventRevision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      uint32                 `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	ObservedAt    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	IngestedAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=ingested_at,json=ingestedAt,proto3" json:"ingested_at,omitempty"`
	Event         *Event                 `protobuf:"bytes,4,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventRevision) Reset() {
	*x = EventRevision{}
	mi := &file_grid_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventRevision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventRevision) ProtoMessage() {}

func (x *EventRevision) ProtoReflect() protoreflect.Message {
	mi := &file_grid_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventRevision.ProtoReflect.Descriptor instead.
func (*EventRevision) Descriptor() ([]byte, []int) {
	return file_grid_proto_rawDescGZIP(), []int{15}
}

func (x *EventRevision) GetRevision() uint32 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *EventRevision) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *EventRevision) GetIngestedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IngestedAt
	}
	return nil
}

func (x *EventRevision) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type EventRevisionList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revisions     []*EventRevision       `protobuf:"bytes,1,rep,name=revisions,proto3" json:"revisions,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventRevisionList) Reset() {
	*x = EventRevisionList{}
	mi := &file_grid_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventRevisionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventRevisionList) ProtoMessage() {}

func (x *EventRevisionList) ProtoReflect() protoreflect.Message {
	mi := &file_grid_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventRevisionList.ProtoReflect.Descriptor instead.
func (*EventRevisionList) Descriptor() ([]byte, []int) {
	return file_grid_proto_rawDescGZIP(), []int{16}
}

func (x *EventRevisionList) GetRevisions() []*EventRevision {
	if x != nil {
		return x.Revisions
	}
	return nil
}

func (x *EventRevisionList) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type PlaceList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Places        []*Place               `protobuf:"bytes,1,rep,name=places,proto3" json:"places,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceList) Reset() {
	*x = PlaceList{}
	mi := &file_grid_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceList) ProtoMessage() {}

func (x *PlaceList) ProtoReflect() protoreflect.Message {
	mi := &file_grid_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceList.ProtoReflect.Descriptor instead.
func (*PlaceList) Descriptor() ([]byte, []int) {
	return file_grid_proto_rawDescGZIP(), []int{17}
}

func (x *PlaceList) GetPlaces() []*Place {
	if x != nil {
		return x.Places
	}
	return nil
}

type SourceList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sources       []*Source              `protobuf:"bytes,1,rep,name=sources,proto3" json:"sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceList) Reset() {
	*x = SourceList{}
	mi := &file_grid_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceList) ProtoMessage() {}

func (x *SourceList) ProtoReflect() protoreflect.Message {
	mi := &file_grid_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceList.ProtoReflect.Descriptor instead.
func (*SourceList) Descriptor() ([]byte, []int) {
	return file_grid_proto_rawDescGZIP(), []int{18}
}

func (x *SourceList) GetSources() []*Source {
	if x != nil {
		return x.Sources
	}
	return nil
}

var File_grid_proto protoreflect.FileDescriptor

const file_grid_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"grid.proto\x12\agrid.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9b\t\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12$\n" +
	"\x05layer\x18\x02 \x01(\x0e2\x0e.grid.v1.LayerR\x05layer\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12-\n" +
	"\bseverity\x18\x04 \x01(\x0e2\x11.grid.v1.SeverityR\bseverity\x12,\n" +
	"\x06status\x18\x05 \x01(\x0e2\x14.grid.v1.EventStatusR\x06status\x12\x1a\n" +
	"\bheadline\x18\x06 \x01(\tR\bheadline\x12\x18\n" +
	"\asummary\x18\a \x01(\tR\asummary\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"area_label\x18\t \x01(\tR\tareaLabel\x12#\n" +
	"\rcanonical_url\x18\n" +
	" \x01(\tR\fcanonicalUrl\x12-\n" +
	"\bgeometry\x18\v \x01(\v2\x11.grid.v1.GeometryR\bgeometry\x12\x1b\n" +
	"\tplace_ids\x18\f \x03(\tR\bplaceIds\x123\n" +
	"\n" +
	"provenance\x18\r \x01(\v2\x13.grid.v1.ProvenanceR\n" +
	"provenance\x128\n" +
	"\teffective\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\teffective\x124\n" +
	"\aexpires\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\aexpires\x12;\n" +
	"\vobserved_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\x12;\n" +
	"\vingested_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"ingestedAt\x12\x1a\n" +
	"\brevision\x18\x12 \x01(\rR\brevision\x126\n" +
	"\venhancement\x18\x13 \x01(\v2\x14.grid.v1.EnhancementR\venhancement\x125\n" +
	"\bwildfire\x18\x14 \x01(\v2\x17.grid.v1.WildfireDetailH\x00R\bwildfire\x12;\n" +
	"\n" +
	"evacuation\x18\x15 \x01(\v2\x19.grid.v1.EvacuationDetailH\x00R\n" +
	"evacuation\x12B\n" +
	"\rweather_alert\x18\x16 \x01(\v2\x1b.grid.v1.WeatherAlertDetailH\x00R\fweatherAlert\x12?\n" +
	"\ffire_weather\x18\x17 \x01(\v2\x1a.grid.v1.FireWeatherDetailH\x00R\vfireWeather\x12;\n" +
	"\n" +
	"earthquake\x18\x18 \x01(\v2\x19.grid.v1.EarthquakeDetailH\x00R\n" +
	"earthquake\x12B\n" +
	"\rroad_incident\x18\x19 \x01(\v2\x1b.grid.v1.RoadIncidentDetailH\x00R\froadIncidentB\b\n" +
	"\x06detailJ\x04\b\x1a\x10\x1f\"{\n" +
	"\bGeometry\x12\x18\n" +
	"\ageojson\x18\x01 \x01(\fR\ageojson\x12(\n" +
	"\x04bbox\x18\x02 \x01(\v2\x14.grid.v1.BoundingBoxR\x04bbox\x12+\n" +
	"\bcentroid\x18\x03 \x01(\v2\x0f.grid.v1.LatLngR\bcentroid\"q\n" +
	"\vBoundingBox\x12\x17\n" +
	"\amin_lat\x18\x01 \x01(\x01R\x06minLat\x12\x17\n" +
	"\amin_lng\x18\x02 \x01(\x01R\x06minLng\x12\x17\n" +
	"\amax_lat\x18\x03 \x01(\x01R\x06maxLat\x12\x17\n" +
	"\amax_lng\x18\x04 \x01(\x01R\x06maxLng\",\n" +
	"\x06LatLng\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x02 \x01(\x01R\x03lng\"\xc6\x01\n" +
	"\n" +
	"Provenance\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12\x1f\n" +
	"\vsource_name\x18\x02 \x01(\tR\n" +
	"sourceName\x12 \n" +
	"\vattribution\x18\x03 \x01(\tR\vattribution\x12\x1d\n" +
	"\n" +
	"source_url\x18\x04 \x01(\tR\tsourceUrl\x129\n" +
	"\n" +
	"fetched_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tfetchedAt\"\xae\x01\n" +
	"\vEnhancement\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12;\n" +
	"\venhanced_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"enhancedAt\x12\x16\n" +
	"\x06fields\x18\x03 \x03(\tR\x06fields\x12\x18\n" +
	"\arequest\x18\x04 \x01(\tR\arequest\x12\x1a\n" +
	"\bresponse\x18\x05 \x01(\tR\bresponse\"\xdd\x03\n" +
	"\x06Source\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vattribution\x18\x03 \x01(\tR\vattribution\x12!\n" +
	"\fhomepage_url\x18\x04 \x01(\tR\vhomepageUrl\x122\n" +
	"\x15poll_interval_seconds\x18\x05 \x01(\rR\x13pollIntervalSeconds\x12.\n" +
	"\x13stale_after_seconds\x18\n" +
	" \x01(\rR\x11staleAfterSeconds\x120\n" +
	"\x14expire_after_seconds\x18\v \x01(\rR\x12expireAfterSeconds\x12B\n" +
	"\x0flast_success_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\rlastSuccessAt\x12B\n" +
	"\x0flast_attempt_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\rlastAttemptAt\x12\x1d\n" +
	"\n" +
	"last_error\x18\b \x01(\tR\tlastError\x12-\n" +
	"\x06status\x18\t \x01(\x0e2\x15.grid.v1.SourceStatusR\x06status\"\xb3\x01\n" +
	"\x05Place\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12&\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x12.grid.v1.PlaceKindR\x04kind\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x04 \x01(\tR\x04slug\x12-\n" +
	"\bgeometry\x18\x05 \x01(\v2\x11.grid.v1.GeometryR\bgeometry\x12\x1b\n" +
	"\tparent_id\x18\x06 \x01(\tR\bparentId\"\x9b\x01\n" +
	"\x0eWildfireDetail\x12\x14\n" +
	"\x05acres\x18\x01 \x01(\x01R\x05acres\x12 \n" +
	"\vcontainment\x18\x02 \x01(\x05R\vcontainment\x12\x16\n" +
	"\x06county\x18\x03 \x01(\tR\x06county\x12\x14\n" +
	"\x05cause\x18\x04 \x01(\tR\x05cause\x12#\n" +
	"\rhas_perimeter\x18\x05 \x01(\bR\fhasPerimeter\"x\n" +
	"\x10EvacuationDetail\x12\x17\n" +
	"\azone_id\x18\x01 \x01(\tR\x06zoneId\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12\x16\n" +
	"\x06county\x18\x04 \x01(\tR\x06county\"\xc4\x01\n" +
	"\x12WeatherAlertDetail\x12!\n" +
	"\fnws_severity\x18\x01 \x01(\tR\vnwsSeverity\x12\x1c\n" +
	"\tcertainty\x18\x02 \x01(\tR\tcertainty\x12\x18\n" +
	"\aurgency\x18\x03 \x01(\tR\aurgency\x12 \n" +
	"\vinstruction\x18\x04 \x01(\tR\vinstruction\x12\x1b\n" +
	"\tarea_desc\x18\x05 \x01(\tR\bareaDesc\x12\x14\n" +
	"\x05zones\x18\x06 \x03(\tR\x05zones\"b\n" +
	"\x11FireWeatherDetail\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12!\n" +
	"\fsource_event\x18\x02 \x01(\tR\vsourceEvent\x12\x14\n" +
	"\x05zones\x18\x03 \x03(\tR\x05zones\"_\n" +
	"\x10EarthquakeDetail\x12\x1c\n" +
	"\tmagnitude\x18\x01 \x01(\x01R\tmagnitude\x12\x19\n" +
	"\bdepth_km\x18\x02 \x01(\x01R\adepthKm\x12\x12\n" +
	"\x04felt\x18\x03 \x01(\x05R\x04felt\"\xeb\x01\n" +
	"\x12RoadIncidentDetail\x12\x1d\n" +
	"\n" +
	"log_number\x18\x01 \x01(\tR\tlogNumber\x12\x16\n" +
	"\x06impact\x18\x02 \x01(\tR\x06impact\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\tR\bduration\x12E\n" +
	"\bmetadata\x18\x04 \x03(\v2).grid.v1.RoadIncidentDetail.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"[\n" +
	"\tEventList\x12&\n" +
	"\x06events\x18\x01 \x03(\v2\x0e.grid.v1.EventR\x06events\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xcb\x01\n" +
	"\rEventRevision\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\rR\brevision\x12;\n" +
	"\vobserved_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\x12;\n" +
	"\vingested_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"ingestedAt\x12$\n" +
	"\x05event\x18\x04 \x01(\v2\x0e.grid.v1.EventR\x05event\"q\n" +
	"\x11EventRevisionList\x124\n" +
	"\trevisions\x18\x01 \x03(\v2\x16.grid.v1.EventRevisionR\trevisions\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"3\n" +
	"\tPlaceList\x12&\n" +
	"\x06places\x18\x01 \x03(\v2\x0e.grid.v1.PlaceR\x06places\"7\n" +
	"\n" +
	"SourceList\x12)\n" +
	"\asources\x18\x01 \x03(\v2\x0f.grid.v1.SourceR\asources*\xca\x01\n" +
	"\x05Layer\x12\x15\n" +
	"\x11LAYER_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bWILDFIRE\x10\x01\x12\x0e\n" +
	"\n" +
	"EVACUATION\x10\x02\x12\x11\n" +
	"\rWEATHER_ALERT\x10\x03\x12\x10\n" +
	"\fFIRE_WEATHER\x10\x04\x12\x0e\n" +
	"\n" +
	"EARTHQUAKE\x10\x05\x12\x11\n" +
	"\rROAD_INCIDENT\x10\x06\x12\t\n" +
	"\x05POWER\x10\n" +
	"\x12\t\n" +
	"\x05GAUGE\x10\v\x12\x0f\n" +
	"\vAIR_QUALITY\x10\f\x12\v\n" +
	"\aNETWORK\x10\r\x12\x10\n" +
	"\fANNOUNCEMENT\x10\x0e*F\n" +
	"\bSeverity\x12\b\n" +
	"\x04INFO\x10\x00\x12\t\n" +
	"\x05MINOR\x10\x01\x12\f\n" +
	"\bMODERATE\x10\x02\x12\n" +
	"\n" +
	"\x06SEVERE\x10\x03\x12\v\n" +
	"\aEXTREME\x10\x04*a\n" +
	"\vEventStatus\x12\x1c\n" +
	"\x18EVENT_STATUS_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tSCHEDULED\x10\x01\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x02\x12\f\n" +
	"\bRESOLVED\x10\x03\x12\v\n" +
	"\aEXPIRED\x10\x04*Q\n" +
	"\fSourceStatus\x12\x1d\n" +
	"\x19SOURCE_STATUS_UNSPECIFIED\x10\x00\x12\x06\n" +
	"\x02OK\x10\x01\x12\t\n" +
	"\x05STALE\x10\x02\x12\x0f\n" +
	"\vUNAVAILABLE\x10\x03*n\n" +
	"\tPlaceKind\x12\x1a\n" +
	"\x16PLACE_KIND_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04AREA\x10\x01\x12\n" +
	"\n" +
	"\x06COUNTY\x10\x02\x12\b\n" +
	"\x04TOWN\x10\x03\x12\r\n" +
	"\tEVAC_ZONE\x10\x04\x12\f\n" +
	"\bCORRIDOR\x10\x05\x12\b\n" +
	"\x04SITE\x10\x06B9Z7github.com/dpup/info.ersn.net/server/api/grid/v1;gridv1b\x06proto3"

var (
	file_grid_proto_rawDescOnce sync.Once
	file_grid_proto_rawDescData []byte
)

func file_grid_proto_rawDescGZIP() []byte {
	file_grid_proto_rawDescOnce.Do(func() {
		file_grid_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grid_proto_rawDesc), len(file_grid_proto_rawDesc)))
	})
	return file_grid_proto_rawDescData
}

var file_grid_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_grid_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_grid_proto_goTypes = []any{
	(Layer)(0),                    // 0: grid.v1.Layer
	(Severity)(0),                 // 1: grid.v1.Severity
	(EventStatus)(0),              // 2: grid.v1.EventStatus
	(SourceStatus)(0),             // 3: grid.v1.SourceStatus
	(PlaceKind)(0),                // 4: grid.v1.PlaceKind
	(*Event)(nil),                 // 5: grid.v1.Event
	(*Geometry)(nil),              // 6: grid.v1.Geometry
	(*BoundingBox)(nil),           // 7: grid.v1.BoundingBox
	(*LatLng)(nil),                // 8: grid.v1.LatLng
	(*Provenance)(nil),            // 9: grid.v1.Provenance
	(*Enhancement)(nil),           // 10: grid.v1.Enhancement
	(*Source)(nil),                // 11: grid.v1.Source
	(*Place)(nil),                 // 12: grid.v1.Place
	(*WildfireDetail)(nil),        // 13: grid.v1.WildfireDetail
	(*EvacuationDetail)(nil),      // 14: grid.v1.EvacuationDetail
	(*WeatherAlertDetail)(nil),    // 15: grid.v1.WeatherAlertDetail
	(*FireWeatherDetail)(nil),     // 16: grid.v1.FireWeatherDetail
	(*EarthquakeDetail)(nil),      // 17: grid.v1.EarthquakeDetail
	(*RoadIncidentDetail)(nil),    // 18: grid.v1.RoadIncidentDetail
	(*EventList)(nil),             // 19: grid.v1.EventList
	(*EventRevision)(nil),         // 20: grid.v1.EventRevision
	(*EventRevisionList)(nil),     // 21: grid.v1.EventRevisionList
	(*PlaceList)(nil),             // 22: grid.v1.PlaceList
	(*SourceList)(nil),            // 23: grid.v1.SourceList
	nil,                           // 24: grid.v1.RoadIncidentDetail.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 25: google.protobuf.Timestamp
}
var file_grid_proto_depIdxs = []int32{
	0,  // 0: grid.v1.Event.layer:type_name -> grid.v1.Layer
	1,  // 1: grid.v1.Event.severity:type_name -> grid.v1.Severity
	2,  // 2: grid.v1.Event.status:type_name -> grid.v1.EventStatus
	6,  // 3: grid.v1.Event.geometry:type_name -> grid.v1.Geometry
	9,  // 4: grid.v1.Event.provenance:type_name -> grid.v1.Provenance
	25, // 5: grid.v1.Event.effective:type_name -> google.protobuf.Timestamp
	25, // 6: grid.v1.Event.expires:type_name -> google.protobuf.Timestamp
	25, // 7: grid.v1.Event.observed_at:type_name -> google.protobuf.Timestamp
	25, // 8: grid.v1.Event.ingested_at:type_name -> google.protobuf.Timestamp
	10, // 9: grid.v1.Event.enhancement:type_name -> grid.v1.Enhancement
	13, // 10: grid.v1.Event.wildfire:type_name -> grid.v1.WildfireDetail
	14, // 11: grid.v1.Event.evacuation:type_name -> grid.v1.EvacuationDetail
	15, // 12: grid.v1.Event.weather_alert:type_name -> grid.v1.WeatherAlertDetail
	16, // 13: grid.v1.Event.fire_weather:type_name -> grid.v1.FireWeatherDetail
	17, // 14: grid.v1.Event.earthquake:type_name -> grid.v1.EarthquakeDetail
	18, // 15: grid.v1.Event.road_incident:type_name -> grid.v1.RoadIncidentDetail
	7,  // 16: grid.v1.Geometry.bbox:type_name -> grid.v1.BoundingBox
	8,  // 17: grid.v1.Geometry.centroid:type_name -> grid.v1.LatLng
	25, // 18: grid.v1.Provenance.fetched_at:type_name -> google.protobuf.Timestamp
	25, // 19: grid.v1.Enhancement.enhanced_at:type_name -> google.protobuf.Timestamp
	25, // 20: grid.v1.Source.last_success_at:type_name -> google.protobuf.Timestamp
	25, // 21: grid.v1.Source.last_attempt_at:type_name -> google.protobuf.Timestamp
	3,  // 22: grid.v1.Source.status:type_name -> grid.v1.SourceStatus
	4,  // 23: grid.v1.Place.kind:type_name -> grid.v1.PlaceKind
	6,  // 24: grid.v1.Place.geometry:type_name -> grid.v1.Geometry
	24, // 25: grid.v1.RoadIncidentDetail.metadata:type_name -> grid.v1.RoadIncidentDetail.MetadataEntry
	5,  // 26: grid.v1.EventList.events:type_name -> grid.v1.Event
	25, // 27: grid.v1.EventRevision.observed_at:type_name -> google.protobuf.Timestamp
	25, // 28: grid.v1.EventRevision.ingested_at:type_name -> google.protobuf.Timestamp
	5,  // 29: grid.v1.EventRevision.event:type_name -> grid.v1.Event
	20, // 30: grid.v1.EventRevisionList.revisions:type_name -> grid.v1.EventRevision
	12, // 31: grid.v1.PlaceList.places:type_name -> grid.v1.Place
	11, // 32: grid.v1.SourceList.sources:type_name -> grid.v1.Source
	33, // [33:33] is the sub-list for method output_type
	33, // [33:33] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_grid_proto_init() }
func file_grid_proto_init() {
	if File_grid_proto != nil {
		return
	}
	file_grid_proto_msgTypes[0].OneofWrappers = []any{
		(*Event_Wildfire)(nil),
		(*Event_Evacuation)(nil),
		(*Event_WeatherAlert)(nil),
		(*Event_FireWeather)(nil),
		(*Event_Earthquake)(nil),
		(*Event_RoadIncident)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grid_proto_rawDesc), len(file_grid_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grid_proto_goTypes,
		DependencyIndexes: file_grid_proto_depIdxs,
		EnumInfos:         file_grid_proto_enumTypes,
		MessageInfos:      file_grid_proto_msgTypes,
	}.Build()
	File_grid_proto = out.File
	file_grid_proto_goTypes = nil
	file_grid_proto_depIdxs = nil
}
