// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: grid.proto

package gridv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GridService_ListSources_FullMethodName = "/grid.v1.GridService/ListSources"
)

// GridServiceClient is the client API for GridService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GridService is the read-only /api/v1 entity + query surface (gRPC-Gateway).
// Ported endpoint-by-endpoint from the hand-built /v1 handlers; see
// docs/grpc-gateway-migration-plan.md §7 for the full endpoint map.
type GridServiceClient interface {
	// ListSources returns the source registry with per-source health — the
	// honesty mechanism clients key layer trust off.
	ListSources(ctx context.Context, in *ListSourcesRequest, opts ...grpc.CallOption) (*SourceList, error)
}

type gridServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGridServiceClient(cc grpc.ClientConnInterface) GridServiceClient {
	return &gridServiceClient{cc}
}

func (c *gridServiceClient) ListSources(ctx context.Context, in *ListSourcesRequest, opts ...grpc.CallOption) (*SourceList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SourceList)
	err := c.cc.Invoke(ctx, GridService_ListSources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GridServiceServer is the server API for GridService service.
// All implementations must embed UnimplementedGridServiceServer
// for forward compatibility.
//
// GridService is the read-only /api/v1 entity + query surface (gRPC-Gateway).
// Ported endpoint-by-endpoint from the hand-built /v1 handlers; see
// docs/grpc-gateway-migration-plan.md §7 for the full endpoint map.
type GridServiceServer interface {
	// ListSources returns the source registry with per-source health — the
	// honesty mechanism clients key layer trust off.
	ListSources(context.Context, *ListSourcesRequest) (*SourceList, error)
	mustEmbedUnimplementedGridServiceServer()
}

// UnimplementedGridServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGridServiceServer struct{}

func (UnimplementedGridServiceServer) ListSources(context.Context, *ListSourcesRequest) (*SourceList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSources not implemented")
}
func (UnimplementedGridServiceServer) mustEmbedUnimplementedGridServiceServer() {}
func (UnimplementedGridServiceServer) testEmbeddedByValue()                     {}

// UnsafeGridServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GridServiceServer will
// result in compilation errors.
type UnsafeGridServiceServer interface {
	mustEmbedUnimplementedGridServiceServer()
}

func RegisterGridServiceServer(s grpc.ServiceRegistrar, srv GridServiceServer) {
	// If the following call pancis, it indicates UnimplementedGridServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GridService_ServiceDesc, srv)
}

func _GridService_ListSources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GridServiceServer).ListSources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GridService_ListSources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GridServiceServer).ListSources(ctx, req.(*ListSourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GridService_ServiceDesc is the grpc.ServiceDesc for GridService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GridService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grid.v1.GridService",
	HandlerType: (*GridServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSources",
			Handler:    _GridService_ListSources_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grid.proto",
}
